/**
 * Word list for Melio Wordle. ~400 common 5-letter English words.
 * Both the daily answer pool and the dictionary of accepted guesses.
 * Curated to avoid plurals ending in -s where possible, slurs, very
 * obscure terms, and proper nouns.
 *
 * Add words by appending to the array — they'll be eligible immediately.
 * Removing words shifts the daily mapping, so prefer to append.
 */

export const WORDS: readonly string[] = [
  "abide", "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult", "after",
  "again", "agent", "agree", "ahead", "alarm", "album", "alert", "alike", "alive", "allow",
  "alone", "along", "alter", "among", "anger", "angle", "angry", "apart", "apple", "apply",
  "arena", "argue", "arise", "armor", "array", "aside", "asset", "audio", "audit", "avoid",
  "awake", "award", "aware", "badly", "baker", "bases", "basic", "basis", "beach", "began",
  "begin", "begun", "being", "below", "bench", "billy", "birth", "black", "blade", "blame",
  "blank", "blast", "blend", "bless", "blind", "block", "blood", "bloom", "blown", "bluff",
  "blunt", "board", "boast", "boost", "booth", "bound", "boxer", "brace", "brain", "brake",
  "brand", "brave", "bread", "break", "breed", "brick", "brief", "bring", "broad", "broke",
  "brown", "brush", "build", "built", "burst", "buyer", "cabin", "cable", "calm", "candy",
  "cargo", "carry", "carve", "catch", "cause", "chain", "chair", "chalk", "chant", "chaos",
  "charm", "chart", "chase", "cheap", "cheat", "check", "chess", "chest", "chief", "child",
  "chime", "chip", "choke", "choir", "chord", "chose", "chunk", "civic", "civil", "claim",
  "clamp", "clash", "class", "clean", "clear", "clerk", "click", "cliff", "climb", "clock",
  "close", "cloth", "cloud", "clown", "clump", "coach", "coast", "couch", "could", "count",
  "court", "cover", "crack", "craft", "cramp", "crane", "crash", "crate", "crawl", "craze",
  "crazy", "cream", "creek", "crest", "crime", "crisp", "cross", "crowd", "crown", "crude",
  "cruel", "crumb", "crush", "crust", "cubic", "curse", "curve", "cycle", "daily", "dairy",
  "dance", "dated", "dealt", "death", "debit", "debut", "delay", "delta", "dense", "depot",
  "depth", "diary", "dirty", "ditch", "diver", "dodge", "doing", "donor", "doubt", "draft",
  "drain", "drama", "drank", "draw", "dread", "dream", "dress", "drift", "drill", "drink",
  "drive", "drone", "drown", "drunk", "dwarf", "eager", "eagle", "early", "earth", "eight",
  "elbow", "elder", "elect", "elite", "elope", "empty", "enemy", "enjoy", "enter", "entry",
  "equal", "equip", "error", "essay", "ethic", "event", "every", "evoke", "exact", "exile",
  "exist", "expel", "extra", "fable", "faced", "fault", "favor", "feast", "feign", "fence",
  "ferry", "fewer", "field", "fiery", "fifth", "fifty", "fight", "final", "first", "fixed",
  "flame", "flash", "flask", "fleet", "flesh", "flick", "flier", "fling", "flint", "float",
  "flock", "flood", "floor", "flour", "flown", "fluid", "flush", "focal", "focus", "folly",
  "force", "forge", "forte", "forth", "forty", "forum", "found", "frame", "frank", "fraud",
  "fresh", "front", "frost", "frown", "fruit", "fudge", "fully", "funny", "gamer", "gaunt",
  "ghost", "giant", "given", "glade", "gland", "glare", "glass", "gleam", "glide", "globe",
  "gloom", "glory", "gloss", "glove", "glyph", "gnash", "gnome", "going", "grace", "grade",
  "grain", "grand", "grant", "grape", "graph", "grasp", "grass", "grave", "great", "greed",
  "green", "greet", "grief", "grill", "grind", "grins", "groom", "gross", "group", "grove",
  "grown", "guard", "guess", "guest", "guide", "guild", "gully", "habit", "hairy", "halve",
  "handy", "hardy", "harsh", "haste", "hatch", "haunt", "heart", "heavy", "hedge", "hefty",
  "helix", "hello", "henry", "herald", "hinge", "hoist", "honey", "honor", "horde", "horse",
  "hotel", "house", "hover", "human", "humid", "humor", "hurry", "hyena", "icily", "ideal",
  "idiot", "image", "imply", "index", "inert", "infer", "ingot", "inlay", "inner", "input",
  "irony", "islet", "issue", "ivory", "jaded", "jelly", "jewel", "joint", "jolly", "joust",
  "judge", "juice", "jumbo", "juror", "kayak", "kebab", "ketch", "khaki", "kiosk", "kitty",
  "knack", "knead", "kneel", "knelt", "knife", "knock", "knoll", "known", "label", "labor",
  "laden", "lance", "lapse", "large", "laser", "later", "laugh", "layer", "leach", "leafy",
  "lean", "leapt", "learn", "lease", "leash", "least", "leave", "ledge", "legal", "lemon",
  "lever", "light", "liked", "limit", "linen", "liner", "lingo", "lipid", "liver", "lobby",
  "local", "lodge", "logic", "loose", "lorry", "loser", "lotus", "lower", "loyal", "lucid",
  "lucky", "lunar", "lunch", "lurid", "lurch", "lyric", "macho", "madam", "magic", "major",
  "maker", "mango", "manor", "maple", "march", "marsh", "match", "matte", "maybe", "mayor",
  "media", "medic", "melon", "melts", "merge", "merit", "merry", "messy", "metal", "meter",
  "metro", "micro", "midst", "might", "milky", "mimic", "miner", "minor", "minty", "mirth",
  "miser", "misty", "mocha", "model", "modem", "moist", "molar", "money", "month", "moose",
  "moral", "motel", "motif", "motor", "motto", "mount", "mourn", "mouse", "mouth", "movie",
  "mover", "muddy", "mulch", "mummy", "mural", "music", "myrrh", "naive", "naked", "nasty",
  "natal", "naval", "needy", "nerve", "never", "newer", "newly", "ninja", "ninth", "noble",
  "nobly", "noise", "north", "notch", "noted", "novel", "nudge", "nurse", "nylon", "oasis",
  "occur", "ocean", "octal", "ocher", "offer", "often", "olive", "onset", "opera", "orbit",
  "order", "organ", "other", "otter", "ought", "ounce", "outer", "outdo", "owner", "ozone",
  "paddy", "pagan", "paint", "panel", "panic", "pansy", "paper", "parry", "parts", "party",
  "pasta", "paste", "patch", "pause", "peace", "peach", "pearl", "pecan", "perch", "petal",
  "phase", "phone", "photo", "piano", "piece", "piety", "piggy", "pilot", "pinch", "pinto",
  "pivot", "pixel", "pizza", "place", "plain", "plait", "plane", "plank", "plant", "plate",
  "plaza", "plead", "pluck", "plumb", "plume", "plunk", "plush", "poach", "point", "poise",
  "polar", "polka", "porch", "posit", "pouch", "pound", "power", "prank", "press", "price",
  "pride", "prime", "primp", "print", "prior", "prism", "prize", "probe", "prone", "proof",
  "proud", "prove", "proxy", "prude", "prune", "psalm", "pulse", "punch", "puppy", "purer",
  "purge", "purse", "pussy", "quack", "quail", "quake", "qualm", "quarry", "quart", "quash",
  "quasi", "queen", "queer", "quell", "query", "quest", "queue", "quick", "quiet", "quill",
  "quilt", "quirk", "quite", "quota", "quote", "rabid", "racer", "radar", "radii", "radio",
  "rainy", "raise", "rajah", "rally", "ralph", "ramen", "ranch", "range", "rapid", "rarer",
  "raspy", "ratio", "raven", "razor", "reach", "react", "ready", "realm", "rebel", "rebut",
  "recap", "regal", "relax", "relay", "remit", "renal", "repay", "reply", "rerun", "reset",
  "retch", "retro", "reuse", "revel", "rhino", "rider", "ridge", "rifle", "right", "rigid",
  "rinse", "ripen", "riser", "risky", "rival", "river", "rivet", "roast", "robin", "robot",
  "rocky", "rodeo", "roger", "rogue", "roost", "rotor", "rouge", "rough", "round", "rouse",
  "route", "royal", "ruddy", "ruler", "rumor", "rupee", "rural", "saber", "sable", "sadly",
  "safer", "saint", "salad", "salon", "salsa", "salty", "salvo", "sandy", "sappy", "sassy",
  "satin", "satyr", "sauce", "sauna", "saute", "savor", "savoy", "savvy", "scald", "scale",
  "scalp", "scaly", "scamp", "scant", "scare", "scary", "scene", "scent", "scion", "scoff",
  "scold", "scoop", "scope", "score", "scorn", "scour", "scout", "scrap", "scree", "screw",
  "scrub", "scuba", "scuff", "seedy", "segue", "seize", "semis", "sense", "sepia", "serge",
  "serif", "serum", "serve", "setup", "seven", "sever", "sewer", "shack", "shade", "shady",
  "shaft", "shake", "shaky", "shale", "shall", "shame", "shape", "shard", "share", "shark",
  "sharp", "sheaf", "shear", "sheen", "sheep", "sheer", "sheet", "shelf", "shell", "shied",
  "shift", "shine", "shiny", "shire", "shirk", "shirt", "shoal", "shock", "shoot", "shore",
  "short", "shown", "shrew", "shrug", "shuck", "shunt", "shush", "shyly", "siege", "sieve",
  "sight", "sigma", "silky", "silly", "since", "sinew", "siren", "sissy", "sixth", "sixty",
  "skate", "skiff", "skill", "skimp", "skirt", "skulk", "skull", "skunk", "slack", "slain",
  "slang", "slant", "slash", "slate", "sleek", "sleep", "sleet", "slept", "slice", "slick",
  "slide", "slime", "slimy", "sling", "slink", "sloop", "slope", "slosh", "sloth", "slump",
  "slung", "slunk", "slurp", "slush", "small", "smart", "smash", "smear", "smell", "smile",
  "smirk", "smite", "smith", "smock", "smoke", "smoky", "smote", "snack", "snail", "snake",
  "snaky", "snare", "snarl", "sneak", "sneer", "snide", "sniff", "snipe", "snore", "snort",
  "snout", "snowy", "soapy", "sober", "soggy", "solar", "solid", "solve", "sonar", "sonic",
  "sooth", "sorry", "sound", "south", "space", "spade", "spank", "spare", "spark", "spasm",
  "spawn", "speak", "spear", "speck", "speed", "spell", "spelt", "spend", "spent", "sperm",
  "spice", "spicy", "spied", "spiel", "spike", "spiky", "spill", "spilt", "spine", "spiny",
  "spire", "spite", "splat", "split", "spoil", "spoke", "spoof", "spook", "spool", "spoon",
  "spore", "sport", "spout", "spray", "spree", "sprig", "spunk", "spurn", "spurt", "squad",
  "squat", "squib", "stack", "staff", "stage", "staid", "stain", "stair", "stake", "stale",
  "stalk", "stall", "stamp", "stand", "stank", "stare", "stark", "start", "stash", "state",
  "stave", "stead", "steak", "steal", "steam", "steed", "steel", "steep", "steer", "stein",
  "stern", "stick", "stiff", "still", "stilt", "sting", "stink", "stint", "stock", "stoic",
  "stoke", "stole", "stomp", "stone", "stony", "stood", "stool", "stoop", "store", "stork",
  "storm", "story", "stout", "stove", "strap", "straw", "stray", "strip", "strut", "stuck",
  "study", "stuff", "stump", "stung", "stunk", "stunt", "style", "suave", "sugar", "suite",
  "sulky", "sunny", "super", "surge", "surly", "sushi", "swami", "swamp", "swarm", "swash",
  "swath", "swear", "sweat", "sweep", "sweet", "swell", "swept", "swift", "swill", "swine",
  "swing", "swirl", "swish", "swoon", "swoop", "sword", "swore", "sworn", "swung", "synod",
  "syrup", "tabby", "table", "taboo", "tacit", "tacky", "taffy", "taint", "taken", "taker",
  "tally", "talon", "tamer", "tango", "tangy", "taper", "tapir", "tardy", "tarot", "taste",
  "tasty", "tatty", "taunt", "tawny", "teach", "teary", "tease", "teddy", "teeth", "tempo",
  "tenor", "tense", "tenth", "tepee", "tepid", "terse", "testy", "thank", "theft", "their",
  "theme", "there", "these", "theta", "thick", "thief", "thigh", "thing", "think", "third",
  "thong", "thorn", "those", "three", "threw", "throb", "throw", "thrum", "thumb", "thump",
  "thyme", "tiara", "tibia", "tidal", "tiger", "tight", "tilde", "timer", "timid", "tipsy",
  "titan", "tithe", "title", "toast", "today", "toddy", "token", "tonal", "tonga", "tonic",
  "tooth", "topaz", "topic", "torch", "torso", "torus", "total", "totem", "touch", "tough",
  "tower", "toxic", "toxin", "trace", "track", "trade", "trail", "train", "trait", "tramp",
  "trash", "trawl", "tread", "treat", "trend", "triad", "trial", "tribe", "trice", "trick",
  "tried", "tripe", "trite", "troll", "troop", "trope", "trout", "trove", "truce", "truck",
  "truly", "trump", "trunk", "truss", "trust", "truth", "tryst", "tubal", "tuber", "tulip",
  "tulle", "tuner", "tunic", "turbo", "tutor", "twang", "tweak", "tweed", "tweet", "twice",
  "twine", "twirl", "twist", "twixt", "tying", "udder", "ulcer", "ultra", "umbra", "uncle",
  "uncut", "under", "undid", "undue", "unfed", "unfit", "unify", "union", "unite", "unity",
  "unlit", "unmet", "unset", "untie", "until", "unwed", "unzip", "upper", "upset", "urban",
  "urine", "usage", "usher", "using", "usual", "utile", "utter", "vague", "valet", "valid",
  "valor", "value", "valve", "vapid", "vapor", "vault", "vaunt", "vegan", "venom", "venue",
  "verge", "verse", "verso", "verve", "vicar", "video", "vigil", "vigor", "villa", "vinyl",
  "viola", "viper", "viral", "virus", "visit", "visor", "vista", "vital", "vivid", "vixen",
  "vocal", "vodka", "vogue", "voice", "voila", "vomit", "voter", "vouch", "vowel", "vying",
  "wacky", "wafer", "wager", "wagon", "waist", "waive", "waltz", "warty", "waste", "watch",
  "water", "waver", "waxen", "weary", "weave", "wedge", "weedy", "weigh", "weird", "welsh",
  "wench", "whack", "whale", "wharf", "wheat", "wheel", "whelp", "where", "which", "whiff",
  "while", "whine", "whiny", "whirl", "whisk", "white", "whole", "whoop", "whose", "widen",
  "wider", "widow", "width", "wield", "wight", "willy", "wimpy", "wince", "winch", "windy",
  "wiser", "wispy", "witch", "witty", "woken", "woman", "world", "worry", "worse", "worth",
  "would", "wound", "woven", "wrath", "wreak", "wreck", "wrest", "wring", "wrist", "write",
  "wrong", "wrote", "wrung", "wryly", "yacht", "yearn", "yeast", "yield", "young", "youth",
  "zebra", "zesty", "zonal"
] as const;

/** Lowercase set for fast guess validation. */
export const WORD_SET: ReadonlySet<string> = new Set(WORDS);

export function isValidGuess(word: string): boolean {
  return WORD_SET.has(word.toLowerCase());
}
