/**
 * Word lists for Melio Wordle.
 *
 * Two-tier system, same shape as the original Wordle:
 *
 *   - ANSWER_WORDS (~400 curated): used as the daily answer pool. These
 *     are common, clean, non-plural-of-noun, no-proper-noun, etc. — the
 *     kind of word that's fair to expect a player to solve.
 *
 *   - EXTRA_GUESSES (~3000+ broader 5-letter words): only used to
 *     validate guesses, never picked as a daily answer. Includes
 *     popular Wordle openers (ADIEU, ARISE, STARE, CRATE, RAISE,
 *     SAUTE, etc.), past tenses, plurals, less-common but real
 *     English words.
 *
 * Adding to ANSWER_WORDS is what changes which puzzles users see; the
 * daily picker uses only that list. Adding to EXTRA_GUESSES just lets
 * more guesses through and is safe to do freely.
 *
 * All words are lowercase. The `WORD_SET` below is the union, used by
 * `isValidGuess()`.
 */

export const ANSWER_WORDS: readonly string[] = [
  "abide", "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult", "after",
  "again", "agent", "agree", "ahead", "alarm", "album", "alert", "alike", "alive", "allow",
  "alone", "along", "alter", "among", "anger", "angle", "angry", "apart", "apple", "apply",
  "arena", "argue", "arise", "armor", "array", "aside", "asset", "audio", "audit", "avoid",
  "awake", "award", "aware", "badly", "baker", "bases", "basic", "basis", "beach", "began",
  "begin", "begun", "being", "below", "bench", "billy", "birth", "black", "blade", "blame",
  "blank", "blast", "blend", "bless", "blind", "block", "blood", "bloom", "blown", "bluff",
  "blunt", "board", "boast", "boost", "booth", "bound", "boxer", "brace", "brain", "brake",
  "brand", "brave", "bread", "break", "breed", "brick", "brief", "bring", "broad", "broke",
  "brown", "brush", "build", "built", "burst", "buyer", "cabin", "cable", "candy",
  "cargo", "carry", "carve", "catch", "cause", "chain", "chair", "chalk", "chant", "chaos",
  "charm", "chart", "chase", "cheap", "cheat", "check", "chess", "chest", "chief", "child",
  "chime", "choke", "choir", "chord", "chose", "chunk", "civic", "civil", "claim",
  "clamp", "clash", "class", "clean", "clear", "clerk", "click", "cliff", "climb", "clock",
  "close", "cloth", "cloud", "clown", "clump", "coach", "coast", "couch", "could", "count",
  "court", "cover", "crack", "craft", "cramp", "crane", "crash", "crate", "crawl", "craze",
  "crazy", "cream", "creek", "crest", "crime", "crisp", "cross", "crowd", "crown", "crude",
  "cruel", "crumb", "crush", "crust", "cubic", "curse", "curve", "cycle", "daily", "dairy",
  "dance", "dated", "dealt", "death", "debit", "debut", "delay", "delta", "dense", "depot",
  "depth", "diary", "dirty", "ditch", "diver", "dodge", "doing", "donor", "doubt", "draft",
  "drain", "drama", "drank", "dread", "dream", "dress", "drift", "drill", "drink",
  "drive", "drone", "drown", "drunk", "dwarf", "eager", "eagle", "early", "earth", "eight",
  "elbow", "elder", "elect", "elite", "elope", "empty", "enemy", "enjoy", "enter", "entry",
  "equal", "equip", "error", "essay", "ethic", "event", "every", "evoke", "exact", "exile",
  "exist", "expel", "extra", "fable", "faced", "fault", "favor", "feast", "feign", "fence",
  "ferry", "fewer", "field", "fiery", "fifth", "fifty", "fight", "final", "first", "fixed",
  "flame", "flash", "flask", "fleet", "flesh", "flick", "flier", "fling", "flint", "float",
  "flock", "flood", "floor", "flour", "flown", "fluid", "flush", "focal", "focus", "folly",
  "force", "forge", "forte", "forth", "forty", "forum", "found", "frame", "frank", "fraud",
  "fresh", "front", "frost", "frown", "fruit", "fudge", "fully", "funny", "gamer", "gaunt",
  "ghost", "giant", "given", "glade", "gland", "glare", "glass", "gleam", "glide", "globe",
  "gloom", "glory", "gloss", "glove", "glyph", "gnash", "gnome", "going", "grace", "grade",
  "grain", "grand", "grant", "grape", "graph", "grasp", "grass", "grave", "great", "greed",
  "green", "greet", "grief", "grill", "grind", "groom", "gross", "group", "grove",
  "grown", "guard", "guess", "guest", "guide", "guild", "gully", "habit", "hairy", "halve",
  "handy", "hardy", "harsh", "haste", "hatch", "haunt", "heart", "heavy", "hedge", "hefty",
  "helix", "hello", "hinge", "hoist", "honey", "honor", "horde", "horse",
  "hotel", "house", "hover", "human", "humid", "humor", "hurry", "hyena", "icily", "ideal",
  "idiot", "image", "imply", "index", "inert", "infer", "ingot", "inlay", "inner", "input",
  "irony", "islet", "issue", "ivory", "jaded", "jelly", "jewel", "joint", "jolly", "joust",
  "judge", "juice", "jumbo", "juror", "kayak", "kebab", "ketch", "khaki", "kiosk", "kitty",
  "knack", "knead", "kneel", "knelt", "knife", "knock", "knoll", "known", "label", "labor",
  "laden", "lance", "lapse", "large", "laser", "later", "laugh", "layer", "leach", "leafy",
  "leapt", "learn", "lease", "leash", "least", "leave", "ledge", "legal", "lemon",
  "lever", "light", "liked", "limit", "linen", "liner", "lingo", "lipid", "liver", "lobby",
  "local", "lodge", "logic", "loose", "lorry", "loser", "lotus", "lower", "loyal", "lucid",
  "lucky", "lunar", "lunch", "lurid", "lurch", "lyric", "macho", "madam", "magic", "major",
  "maker", "mango", "manor", "maple", "march", "marsh", "match", "matte", "maybe", "mayor",
  "media", "medic", "melon", "melts", "merge", "merit", "merry", "messy", "metal", "meter",
  "metro", "micro", "midst", "might", "milky", "mimic", "miner", "minor", "minty", "mirth",
  "miser", "misty", "mocha", "model", "modem", "moist", "molar", "money", "month", "moose",
  "moral", "motel", "motif", "motor", "motto", "mount", "mourn", "mouse", "mouth", "movie",
  "mover", "muddy", "mulch", "mummy", "mural", "music", "myrrh", "naive", "naked", "nasty",
  "natal", "naval", "needy", "nerve", "never", "newer", "newly", "ninja", "ninth", "noble",
  "nobly", "noise", "north", "notch", "noted", "novel", "nudge", "nurse", "nylon", "oasis",
  "occur", "ocean", "octal", "ocher", "offer", "often", "olive", "onset", "opera", "orbit",
  "order", "organ", "other", "otter", "ought", "ounce", "outer", "owner", "ozone",
  "paddy", "pagan", "paint", "panel", "panic", "pansy", "paper", "parry", "party",
  "pasta", "paste", "patch", "pause", "peace", "peach", "pearl", "pecan", "perch", "petal",
  "phase", "phone", "photo", "piano", "piece", "piety", "piggy", "pilot", "pinch", "pinto",
  "pivot", "pixel", "pizza", "place", "plain", "plait", "plane", "plank", "plant", "plate",
  "plaza", "plead", "pluck", "plumb", "plume", "plunk", "plush", "poach", "point", "poise",
  "polar", "polka", "porch", "posit", "pouch", "pound", "power", "prank", "press", "price",
  "pride", "prime", "primp", "print", "prior", "prism", "prize", "probe", "prone", "proof",
  "proud", "prove", "proxy", "prude", "prune", "psalm", "pulse", "punch", "puppy", "purer",
  "purge", "purse", "quack", "quail", "quake", "qualm", "quart", "quash",
  "quasi", "queen", "queer", "quell", "query", "quest", "queue", "quick", "quiet", "quill",
  "quilt", "quirk", "quite", "quota", "quote", "rabid", "racer", "radar", "radii", "radio",
  "rainy", "raise", "rally", "ramen", "ranch", "range", "rapid", "rarer",
  "raspy", "ratio", "raven", "razor", "reach", "react", "ready", "realm", "rebel", "rebut",
  "recap", "regal", "relax", "relay", "remit", "renal", "repay", "reply", "rerun", "reset",
  "retch", "retro", "reuse", "revel", "rhino", "rider", "ridge", "rifle", "right", "rigid",
  "rinse", "ripen", "riser", "risky", "rival", "river", "rivet", "roast", "robin", "robot",
  "rocky", "rodeo", "rogue", "roost", "rotor", "rouge", "rough", "round", "rouse",
  "route", "royal", "ruddy", "ruler", "rumor", "rupee", "rural", "saber", "sable", "sadly",
  "safer", "saint", "salad", "salon", "salsa", "salty", "salvo", "sandy", "sappy", "sassy",
  "satin", "satyr", "sauce", "sauna", "saute", "savor", "savvy", "scald", "scale",
  "scalp", "scaly", "scamp", "scant", "scare", "scary", "scene", "scent", "scion", "scoff",
  "scold", "scoop", "scope", "score", "scorn", "scour", "scout", "scrap", "screw",
  "scrub", "scuba", "scuff", "seedy", "segue", "seize", "sense", "sepia",
  "serif", "serum", "serve", "setup", "seven", "sever", "sewer", "shack", "shade", "shady",
  "shaft", "shake", "shaky", "shale", "shall", "shame", "shape", "shard", "share", "shark",
  "sharp", "sheaf", "shear", "sheen", "sheep", "sheer", "sheet", "shelf", "shell", "shied",
  "shift", "shine", "shiny", "shire", "shirk", "shirt", "shoal", "shock", "shoot", "shore",
  "short", "shown", "shrew", "shrug", "shuck", "shunt", "shush", "shyly", "siege", "sieve",
  "sight", "sigma", "silky", "silly", "since", "sinew", "siren", "sissy", "sixth", "sixty",
  "skate", "skiff", "skill", "skimp", "skirt", "skulk", "skull", "skunk", "slack", "slain",
  "slang", "slant", "slash", "slate", "sleek", "sleep", "sleet", "slept", "slice", "slick",
  "slide", "slime", "slimy", "sling", "slink", "sloop", "slope", "slosh", "sloth", "slump",
  "slung", "slunk", "slurp", "slush", "small", "smart", "smash", "smear", "smell", "smile",
  "smirk", "smite", "smith", "smock", "smoke", "smoky", "smote", "snack", "snail", "snake",
  "snaky", "snare", "snarl", "sneak", "sneer", "snide", "sniff", "snipe", "snore", "snort",
  "snout", "snowy", "soapy", "sober", "soggy", "solar", "solid", "solve", "sonar", "sonic",
  "sorry", "sound", "south", "space", "spade", "spank", "spare", "spark", "spasm",
  "spawn", "speak", "spear", "speck", "speed", "spell", "spelt", "spend", "spent", "sperm",
  "spice", "spicy", "spied", "spiel", "spike", "spiky", "spill", "spilt", "spine", "spiny",
  "spire", "spite", "splat", "split", "spoil", "spoke", "spoof", "spook", "spool", "spoon",
  "spore", "sport", "spout", "spray", "spree", "sprig", "spunk", "spurn", "spurt", "squad",
  "squat", "squib", "stack", "staff", "stage", "staid", "stain", "stair", "stake", "stale",
  "stalk", "stall", "stamp", "stand", "stank", "stare", "stark", "start", "stash", "state",
  "stave", "stead", "steak", "steal", "steam", "steed", "steel", "steep", "steer", "stein",
  "stern", "stick", "stiff", "still", "stilt", "sting", "stink", "stint", "stock", "stoic",
  "stoke", "stole", "stomp", "stone", "stony", "stood", "stool", "stoop", "store", "stork",
  "storm", "story", "stout", "stove", "strap", "straw", "stray", "strip", "strut", "stuck",
  "study", "stuff", "stump", "stung", "stunk", "stunt", "style", "suave", "sugar", "suite",
  "sulky", "sunny", "super", "surge", "surly", "sushi", "swami", "swamp", "swarm", "swash",
  "swath", "swear", "sweat", "sweep", "sweet", "swell", "swept", "swift", "swill", "swine",
  "swing", "swirl", "swish", "swoon", "swoop", "sword", "swore", "sworn", "swung", "synod",
  "syrup", "tabby", "table", "taboo", "tacit", "tacky", "taffy", "taint", "taken", "taker",
  "tally", "talon", "tamer", "tango", "tangy", "taper", "tapir", "tardy", "tarot", "taste",
  "tasty", "tatty", "taunt", "tawny", "teach", "teary", "tease", "teddy", "teeth", "tempo",
  "tenor", "tense", "tenth", "tepee", "tepid", "terse", "testy", "thank", "theft", "their",
  "theme", "there", "these", "theta", "thick", "thief", "thigh", "thing", "think", "third",
  "thong", "thorn", "those", "three", "threw", "throb", "throw", "thrum", "thumb", "thump",
  "thyme", "tiara", "tibia", "tidal", "tiger", "tight", "tilde", "timer", "timid", "tipsy",
  "titan", "tithe", "title", "toast", "today", "toddy", "token", "tonal", "tonic",
  "tooth", "topaz", "topic", "torch", "torso", "torus", "total", "totem", "touch", "tough",
  "tower", "toxic", "toxin", "trace", "track", "trade", "trail", "train", "trait", "tramp",
  "trash", "trawl", "tread", "treat", "trend", "triad", "trial", "tribe", "trice", "trick",
  "tried", "tripe", "trite", "troll", "troop", "trope", "trout", "trove", "truce", "truck",
  "truly", "trump", "trunk", "truss", "trust", "truth", "tryst", "tubal", "tuber", "tulip",
  "tulle", "tuner", "tunic", "turbo", "tutor", "twang", "tweak", "tweed", "tweet", "twice",
  "twine", "twirl", "twist", "twixt", "tying", "udder", "ulcer", "ultra", "umbra", "uncle",
  "uncut", "under", "undid", "undue", "unfed", "unfit", "unify", "union", "unite", "unity",
  "unlit", "unmet", "unset", "untie", "until", "unwed", "unzip", "upper", "upset", "urban",
  "urine", "usage", "usher", "using", "usual", "utile", "utter", "vague", "valet", "valid",
  "valor", "value", "valve", "vapid", "vapor", "vault", "vaunt", "vegan", "venom", "venue",
  "verge", "verse", "verso", "verve", "vicar", "video", "vigil", "vigor", "villa", "vinyl",
  "viola", "viper", "viral", "virus", "visit", "visor", "vista", "vital", "vivid", "vixen",
  "vocal", "vodka", "vogue", "voice", "voila", "vomit", "voter", "vouch", "vowel", "vying",
  "wacky", "wafer", "wager", "wagon", "waist", "waive", "waltz", "warty", "waste", "watch",
  "water", "waver", "waxen", "weary", "weave", "wedge", "weedy", "weigh", "weird", "welsh",
  "wench", "whack", "whale", "wharf", "wheat", "wheel", "whelp", "where", "which", "whiff",
  "while", "whine", "whiny", "whirl", "whisk", "white", "whole", "whoop", "whose", "widen",
  "wider", "widow", "width", "wield", "wight", "wimpy", "wince", "winch", "windy",
  "wiser", "wispy", "witch", "witty", "woken", "woman", "world", "worry", "worse", "worth",
  "would", "wound", "woven", "wrath", "wreak", "wreck", "wrest", "wring", "wrist", "write",
  "wrong", "wrote", "wrung", "wryly", "yacht", "yearn", "yeast", "yield", "young", "youth",
  "zebra", "zesty", "zonal",
];

/**
 * Broad acceptance dictionary — popular openers, past tenses, plurals,
 * less-common but real words. Only used for guess validation, NEVER
 * picked as a daily answer.
 *
 * This list won't catch every English 5-letter word, but it covers
 * the ones players actually type. If a real word gets rejected,
 * append it here.
 */
export const EXTRA_GUESSES: readonly string[] = [
  // A
  "aahed", "aalii", "aargh", "abaca", "aback", "abase", "abash", "abate", "abbas", "abbey",
  "abbot", "abeam", "abets", "abhor", "abled", "abler", "abode", "abort", "abuts", "abuzz",
  "abyss", "acerb", "ached", "aches", "achoo", "acids", "acing", "acmes", "acned", "acnes",
  "acorn", "acred", "acres", "acrid", "acted", "actin", "acted", "acyls", "adage", "adapt",
  "added", "adder", "addle", "adieu", "adios", "adits", "adlib", "admen", "admin", "admix",
  "adobe", "adobo", "adore", "adorn", "adown", "adoze", "ADUST", "adyts", "adzes", "aeons",
  "aerie", "afars", "affix", "afire", "afoot", "afore", "afoul", "afros", "agape", "agars",
  "agate", "agave", "agaze", "agers", "agile", "aging", "agios", "aglee", "aglet", "agley",
  "aglow", "agone", "agons", "agony", "agora", "agues", "aheap", "ahold", "ahull", "aided",
  "aider", "aides", "ailed", "aimed", "aimer", "aioli", "aired", "airer", "airns", "aisle",
  "aitch", "ajiva", "ajuga", "akees", "alack", "alans", "alarm", "alate", "albas", "albee",
  "album", "alcid", "alders", "aldol", "aleck", "alecs", "aleph", "alfas", "algae", "algal",
  "algas", "algid", "algin", "algor", "algum", "alias", "alibi", "alien", "align", "alike",
  "aline", "alkyd", "alkyl", "allay", "alley", "allod", "allot", "allow", "alloy", "almah",
  "almas", "alme", "almeh", "almes", "almud", "almug", "aloes", "aloft", "aloha", "aloin",
  "aloud", "alpha", "altar", "alter", "altho", "altos", "alums", "alway", "amahs", "amain",
  "amass", "amaze", "amber", "ambit", "amble", "ambry", "ameba", "ameer", "amend", "amens",
  "amids", "amies", "amiga", "amigo", "amine", "amino", "amins", "amirs", "amiss", "ammos",
  "amole", "among", "amour", "amped", "ample", "amply", "ampul", "amuck", "amuse", "amyls",
  "ancho", "ancon", "andes", "anele", "anent", "angas", "anger", "angle", "anglo", "angry",
  "angst", "anile", "anils", "anima", "anime", "animi", "anion", "anise", "ankhs", "ankle",
  "ankus", "anlas", "annal", "annas", "annex", "annoy", "annul", "anoas", "anode", "anole",
  "anomy", "ansae", "antas", "anted", "antes", "antic", "antis", "antra", "antre", "antsy",
  "anvil", "aorta", "apace", "apart", "apers", "apery", "aphid", "aphis", "apian", "aping",
  "apish", "apnea", "appal", "appel", "apple", "apply", "appro", "apres", "april", "apron",
  "apsis", "apter", "aptly", "aquae", "aquas", "araks", "arbor", "arced", "archs", "areas",
  "areca", "areic", "arena", "arene", "arepa", "argal", "argil", "argle", "argol", "argon",
  "argot", "argue", "argus", "arhat", "arias", "ariel", "ariled", "ariot", "arise", "arius",
  "armed", "armer", "armet", "armor", "aroid", "aroma", "arose", "arpen", "arras", "array",
  "arris", "arrow", "arroz", "arsed", "arses", "arsey", "arsis", "arson", "artal", "artel",
  "artic", "artie", "artsy", "arums", "arval", "arvos", "aryls", "ascot", "ashed", "ashes",
  "aside", "asked", "asker", "askew", "aspen", "asper", "aspic", "assai", "assay", "asses",
  "asset", "aster", "astir", "atilt", "atlas", "atmas", "atman", "atoll", "atoms", "atomy",
  "atone", "atony", "atria", "atrip", "attar", "audio", "audit", "auger", "aught", "augur",
  "aulic", "aunts", "aunty", "aural", "auras", "auric", "auris", "autos", "auxin", "avail",
  "avant", "avast", "avers", "avert", "avgas", "avian", "avion", "aviso", "avoid", "avoue",
  "avows", "await", "awake", "award", "aware", "awash", "awful", "awing", "awned", "awoke",
  "axels", "axial", "axile", "axing", "axion", "axite", "axles", "axman", "axmen", "axons",
  "ayahs", "ayins", "azans", "azide", "azido", "azine", "azoic", "azole", "azons", "azote",
  "azoth", "azuki", "azure",

  // B
  "babas", "babel", "babes", "babka", "baboo", "babul", "bacca", "backs", "bacon", "baddy",
  "badge", "badly", "baels", "bagel", "baggy", "baked", "baker", "bakes", "balas", "balds",
  "baldy", "baled", "baler", "bales", "balks", "balky", "balls", "bally", "balms", "balmy",
  "balsa", "banal", "banco", "bands", "bandy", "baned", "banes", "bangs", "banjo", "banks",
  "barbs", "bards", "bared", "barer", "bares", "barfs", "barge", "barks", "barky", "barms",
  "barmy", "barns", "barny", "baron", "barre", "basal", "based", "bases", "basic", "basil",
  "basin", "basis", "basks", "basso", "baste", "batch", "bated", "bates", "bathe", "baths",
  "batik", "baton", "batts", "batty", "bauds", "baulk", "bawdy", "bawls", "bayed", "bayou",
  "bazoo", "beach", "beads", "beady", "beaks", "beaky", "beams", "beamy", "beano", "beans",
  "beard", "bears", "beast", "beats", "beaus", "beaut", "beaux", "bebop", "becks", "beech",
  "beedi", "beefs", "beefy", "befit", "begat", "beget", "begin", "begot", "begum", "begun",
  "beige", "being", "belay", "belch", "belie", "belle", "belly", "below", "belts", "bench",
  "bends", "bendy", "benne", "benny", "bento", "bents", "beres", "beret", "bergs", "berms",
  "berry", "berth", "beryl", "beset", "besom", "besot", "bests", "betas", "betel", "betta",
  "bevel", "bevvy", "bezel", "bhang", "bhuts", "bialy", "bibbs", "bicep", "biddy", "bided",
  "bides", "bidet", "bifid", "biffs", "biffy", "bight", "bigly", "bigos", "bigot", "bijou",
  "biked", "biker", "bikes", "bikie", "bilge", "bilgy", "bills", "billy", "bimah", "bimas",
  "bimbo", "binal", "binds", "biner", "bines", "binge", "bingo", "binit", "biome", "biont",
  "biota", "biped", "birch", "birds", "birks", "birle", "biros", "birrs", "birse", "birth",
  "bises", "bisks", "bison", "bitch", "biter", "bites", "bitsy", "bitts", "bitty", "blabs",
  "black", "blade", "blaff", "blahs", "blame", "blams", "bland", "blank", "blare", "blase",
  "blast", "blats", "blaze", "bleak", "blear", "bleat", "blebs", "bleed", "bleep", "blend",
  "blent", "bless", "blest", "blets", "blimp", "blimy", "blind", "bling", "blini", "blink",
  "blips", "bliss", "blitz", "blobs", "block", "blocs", "bloke", "blond", "blood", "bloom",
  "bloop", "blots", "blown", "blows", "blowy", "blubs", "blued", "bluer", "blues", "bluet",
  "bluey", "bluff", "blume", "blunt", "blurb", "blurs", "blurt", "blush", "boars", "boast",
  "boats", "bobby", "boded", "bodes", "bogan", "bogey", "boggy", "bogie", "bogus", "boils",
  "boing", "bolas", "bolde", "bolds", "boles", "bolls", "bolos", "bolts", "bolus", "bombe",
  "bombs", "bonds", "boned", "boner", "bones", "boney", "bongo", "bongs", "bonks", "bonny",
  "bonus", "boobs", "booby", "booed", "books", "booms", "boomy", "boons", "boors", "boost",
  "booth", "boots", "booty", "booze", "boozy", "borax", "bored", "borer", "bores", "boric",
  "boron", "bosky", "bosom", "boson", "bossy", "bosun", "botch", "bough", "boule", "bound",
  "bouts", "bowed", "bowel", "bower", "bowls", "boxed", "boxer", "boxes", "bract", "brads",
  "brae", "braes", "brags", "braid", "brain", "brake", "braky", "brand", "brank", "brans",
  "brash", "brass", "brats", "brava", "bravo", "brawl", "brawn", "braws", "brays", "braze",
  "bread", "break", "bream", "breed", "brens", "brent", "brews", "briar", "bribe", "brick",
  "bride", "brief", "brier", "bries", "brigs", "brims", "brine", "bring", "brink", "briny",
  "brios", "brisk", "broad", "brock", "broil", "broke", "brome", "bronc", "brood", "brook",
  "broom", "broth", "brown", "brows", "brrrr", "brunt", "brush", "brusk", "brute", "bubba",
  "bubbe", "bucko", "bucks", "buddy", "budge", "buena", "buffi", "buffo", "buffs", "buggy",
  "bugle", "buhrs", "build", "built", "bulbs", "bulge", "bulgy", "bulks", "bulky", "bulls",
  "bully", "bumph", "bumps", "bumpy", "bunch", "bundt", "bungs", "bunko", "bunks", "bunny",
  "bunts", "buoys", "burbs", "burds", "buret", "burgs", "burka", "burke", "burls", "burly",
  "burns", "burnt", "burps", "burrs", "bursa", "burse", "burst", "busby", "buses", "bushy",
  "busks", "busts", "busty", "butch", "buteo", "butes", "butte", "butts", "butut", "butyl",
  "buyer", "buzz", "bwana", "byres", "byrls", "bytes", "byway",

  // C
  "cabal", "cabby", "caber", "cabin", "cable", "cabob", "cacao", "cache", "cacti", "caddy",
  "cadet", "cadge", "cadgy", "cadis", "cadre", "caeca", "caese", "cafes", "caffs", "caged",
  "cager", "cages", "cagey", "caids", "cains", "cairn", "cajun", "caked", "cakes", "cakey",
  "calfs", "calif", "calix", "calks", "calla", "calls", "calms", "calos", "calve", "calyx",
  "camas", "camel", "cameo", "campo", "camps", "campy", "canal", "candy", "caned", "caner",
  "canes", "canid", "canna", "canny", "canoe", "canon", "canso", "canst", "canto", "cants",
  "caped", "caper", "capes", "capon", "capos", "capus", "carat", "carbs", "cards", "cared",
  "carer", "cares", "caret", "cargo", "carls", "carns", "carny", "carob", "carol", "carom",
  "carpi", "carps", "carrs", "carry", "carse", "carte", "carts", "carve", "casas", "cased",
  "cases", "casks", "casky", "caste", "casts", "casus", "catch", "cater", "cates", "catty",
  "caulk", "cauls", "cause", "cavas", "caved", "caver", "caves", "cavil", "cawed", "cease",
  "cebid", "cecal", "cecum", "cedar", "ceded", "ceder", "cedes", "ceiba", "ceili", "celeb",
  "cello", "cells", "celom", "celts", "cense", "cento", "cents", "ceorl", "ceria", "cered",
  "ceres", "ceric", "ceros", "cesta", "cesti", "cetes", "chads", "chafe", "chaff", "chain",
  "chair", "chalk", "champ", "chams", "chang", "chank", "chant", "chao", "chaos", "chaps",
  "chard", "chare", "chark", "charm", "charr", "chars", "chart", "chary", "chase", "chasm",
  "chats", "chaws", "chays", "cheap", "cheat", "check", "cheek", "cheep", "cheer", "chefs",
  "chela", "chert", "chess", "chest", "cheth", "chevy", "chews", "chewy", "chiao", "chias",
  "chick", "chico", "chics", "chide", "chief", "chiel", "child", "chile", "chili", "chill",
  "chimb", "chime", "chimp", "china", "chine", "chink", "chino", "chins", "chips", "chirk",
  "chirm", "chiro", "chirp", "chirr", "chits", "chive", "chivy", "chock", "choir", "choke",
  "choky", "cholo", "chomp", "chook", "chops", "chord", "chore", "chose", "chott", "chows",
  "chubs", "chuck", "chufa", "chuff", "chugs", "chump", "chums", "chunk", "chuse", "chute",
  "chyle", "chyme", "cibol", "cider", "cigar", "cilia", "cimex", "cinch", "cines", "cions",
  "circa", "cires", "cirri", "cisco", "cissy", "cists", "cited", "citer", "cites", "civet",
  "civic", "civil", "civvy", "clack", "clade", "clads", "claim", "clamp", "clams", "clang",
  "clank", "clans", "claps", "clapt", "claro", "clash", "clasp", "class", "claw", "clays",
  "clean", "clear", "cleat", "cleek", "clefs", "cleft", "clegs", "clepe", "clerk", "clews",
  "click", "cliff", "clift", "climb", "clime", "cline", "cling", "clink", "clips", "clipt",
  "cloak", "clock", "clods", "cloff", "clogs", "clomb", "clomp", "clone", "clons", "clonk",
  "clops", "close", "cloth", "clots", "cloud", "clout", "clove", "clown", "cloys", "clubs",
  "cluck", "clued", "clues", "cluey", "clump", "clung", "clunk", "coach", "coact", "coala",
  "coals", "coaly", "coapt", "coast", "coati", "coats", "cobby", "cobia", "cobra", "cobs",
  "cocas", "cocci", "cocks", "cocky", "cocoa", "cocos", "codas", "coded", "coden", "coder",
  "codes", "codex", "codon", "coeds", "coffs", "cogon", "cohog", "coifs", "coign", "coils",
  "coins", "coirs", "coits", "coked", "cokes", "colas", "colby", "colds", "coled", "coles",
  "colic", "colin", "colly", "colog", "colon", "color", "colts", "colza", "comae", "comal",
  "comas", "combe", "combo", "combs", "comer", "comes", "comet", "comfy", "comic", "comma",
  "commo", "comms", "comps", "comte", "conch", "condo", "coned", "cones", "coney", "conga",
  "conge", "congo", "conic", "conks", "conky", "conns", "conus", "cooch", "cooed", "cooee",
  "cooer", "cooey", "coofs", "cooks", "cooky", "cools", "coomb", "coons", "coops", "coots",
  "copay", "coped", "copen", "coper", "copes", "copra", "copse", "coral", "cords", "cordy",
  "cored", "corer", "cores", "corgi", "coria", "corks", "corky", "corms", "corns", "cornu",
  "corny", "corps", "corse", "cosec", "cosed", "coses", "coset", "cosey", "cosie", "costa",
  "costs", "cotes", "cotta", "couch", "could", "count", "coupe", "coups", "court", "couth",
  "coved", "coven", "cover", "coves", "covet", "covey", "cower", "cowls", "cowry", "coxa",
  "coxal", "coyer", "coyly", "coypu", "cozen", "cozes", "cozey", "cozie", "crabs", "crack",
  "craft", "crags", "cramp", "crams", "crane", "crank", "crape", "craps", "crash", "crass",
  "crate", "crave", "crawl", "craws", "craze", "crazy", "creak", "cream", "credo", "creds",
  "creed", "creek", "creel", "creep", "creme", "crepe", "crept", "crepy", "cress", "crest",
  "crews", "cribs", "crick", "cried", "crier", "cries", "crime", "crimp", "crisp", "crits",
  "croak", "croci", "crock", "crocs", "croft", "crone", "crony", "crook", "crool", "croon",
  "crops", "crore", "cross", "crowd", "crown", "crows", "crude", "cruds", "cruel", "cruet",
  "crumb", "crump", "cruse", "crush", "crust", "crwth", "crypt", "cubby", "cubed", "cuber",
  "cubes", "cubic", "cubit", "cuddy", "cuffs", "cuing", "cukes", "culch", "culet", "culex",
  "culls", "cully", "culms", "culpa", "cults", "cumin", "cunts", "cupel", "cupid", "cuppa",
  "cuppy", "curbs", "curch", "curds", "curdy", "cured", "curer", "cures", "curet", "curfs",
  "curia", "curie", "curio", "curls", "curly", "curns", "currs", "curry", "curse", "cursi",
  "curst", "curve", "curvy", "cusec", "cushy", "cusks", "cusps", "cuspy", "cussy", "cutch",
  "cuter", "cutes", "cutey", "cutie", "cutin", "cutis", "cutty", "cutup", "cycad", "cycas",
  "cycle", "cyclo", "cyder", "cymae", "cymar", "cymas", "cymes", "cymol", "cynic", "cyses",
  "cyst", "cysts", "czars",

  // D
  "dachas", "daces", "dacha", "dadas", "daddy", "dados", "daffs", "daffy", "dagga", "dagos",
  "dahls", "daily", "dairy", "daisy", "dales", "dally", "damar", "dames", "damns", "damps",
  "dance", "dandy", "dared", "darer", "dares", "darks", "darky", "darns", "darts", "dashi",
  "dashy", "dated", "dater", "dates", "datos", "datto", "datum", "daube", "daubs", "dauby",
  "daunt", "davit", "dawks", "dawns", "dazed", "dazes", "deads", "deair", "deals", "dealt",
  "deans", "dears", "deary", "death", "debar", "debit", "debts", "debug", "debut", "debye",
  "decaf", "decal", "decay", "decks", "decor", "decoy", "decry", "deeds", "deedy", "deems",
  "deeps", "deers", "deets", "defer", "defis", "deflag", "deify", "deign", "deism", "deist",
  "deity", "delay", "deled", "deles", "delfs", "delft", "delis", "dells", "delta", "delts",
  "delve", "demit", "demob", "demon", "demos", "demur", "denim", "dense", "dents", "denyl",
  "deort", "depot", "depth", "derby", "deres", "derma", "derms", "desks", "deter", "detox",
  "deuce", "devel", "devil", "devon", "dewed", "dexes", "dexie", "dhals", "dhows", "dials",
  "diary", "diazo", "diced", "dicer", "dices", "dicey", "dicks", "dicky", "dicot", "dicta",
  "didie", "didos", "didst", "diels", "diene", "diets", "digit", "diked", "dikes", "dildo",
  "dills", "dilly", "dimer", "dimes", "dimly", "dinar", "dined", "diner", "dines", "dings",
  "dingy", "dinks", "dinky", "dinos", "dints", "diode", "dippy", "direr", "dirge", "dirks",
  "dirls", "dirts", "dirty", "disco", "discs", "dishy", "disks", "ditch", "ditsy", "ditto",
  "ditty", "ditzy", "divan", "dived", "diver", "dives", "divot", "divvy", "diwan", "dixit",
  "dizzy", "djinn", "djins", "dobby", "dobie", "dobla", "dobra", "dobro", "docks", "dodge",
  "dodgy", "dodos", "doers", "doest", "doeth", "doffs", "dogey", "doggo", "doggy", "dogie",
  "dogma", "doily", "doing", "doits", "dojos", "dolce", "dolci", "doled", "doles", "dolls",
  "dolly", "dolma", "dolor", "dolts", "domed", "domes", "dongs", "donna", "donne", "donor",
  "donsy", "donut", "dooms", "doozy", "doper", "dopes", "dopey", "dorks", "dorky", "dorms",
  "dormy", "dorps", "dorrs", "dorsa", "dorty", "doser", "doses", "dotal", "doted", "doter",
  "dotes", "dotty", "doubt", "dough", "douse", "doved", "doves", "dowdy", "dowed", "dowel",
  "dower", "downs", "downy", "dowry", "dowse", "doxie", "doyen", "dozed", "dozen", "dozer",
  "dozes", "drabs", "draco", "draff", "draft", "drags", "drail", "drain", "drake", "drama",
  "drams", "drank", "drape", "drats", "drave", "drawl", "drawn", "draws", "drays", "dread",
  "dream", "drear", "dreck", "dreed", "dreer", "drees", "dregs", "dreks", "dress", "drest",
  "dribs", "dried", "drier", "dries", "drift", "drill", "drink", "drips", "dript", "drive",
  "droid", "droit", "droll", "drone", "drool", "droop", "drops", "dropt", "dross", "drove",
  "drown", "drubs", "drugs", "druid", "drums", "drunk", "drupe", "druse", "dryad", "dryer",
  "dryly", "duads", "duals", "ducal", "ducat", "ducks", "ducky", "ducts", "dudes", "duels",
  "duets", "duffs", "duits", "duked", "dukes", "dulls", "dully", "dulse", "dumas", "dumbo",
  "dumbs", "dumka", "dumky", "dummy", "dumps", "dumpy", "dunce", "dunch", "dunes", "dungs",
  "dungy", "dunks", "dunno", "duomi", "duomo", "duped", "duper", "dupes", "dural", "duras",
  "dured", "dures", "durns", "duroc", "duros", "durra", "durrs", "durum", "dusks", "dusky",
  "dusts", "dusty", "dutch", "duvet", "dwarf", "dwell", "dwelt", "dyads", "dyers", "dying",
  "dykes", "dynes", "dynel",

  // E
  "eager", "eagle", "eared", "earls", "early", "earns", "earth", "eased", "easel", "eases",
  "easts", "eaten", "eater", "eaves", "ebbed", "ebons", "ebony", "ebook", "echos", "eclat",
  "edema", "edged", "edger", "edges", "edict", "edify", "edits", "educe", "educt", "eells",
  "eensy", "eerie", "egads", "egers", "egest", "eggar", "egged", "egger", "egret", "eider",
  "eidos", "eight", "eikon", "eject", "ekes", "elain", "eland", "elans", "elate", "elbow",
  "elder", "elect", "elegy", "elemi", "elfin", "elide", "elint", "elite", "elope", "elude",
  "elute", "elver", "elves", "email", "embed", "ember", "embow", "emcee", "emeer", "emend",
  "emery", "emits", "emmer", "emmet", "emote", "empty", "enact", "ended", "ender", "endow",
  "enema", "enemy", "enjoy", "ennui", "enols", "enrol", "ensue", "enter", "entry", "envoy",
  "enzym", "eosin", "epact", "epees", "ephas", "ephor", "epics", "epoch", "epode", "epoxy",
  "equal", "equid", "equip", "erase", "erect", "ergot", "erica", "erode", "erose", "erred",
  "error", "eruct", "erupt", "ervil", "essay", "ester", "ethic", "ethos", "ethyl", "etude",
  "etwee", "etyma", "euros", "evade", "event", "every", "evets", "evict", "evils", "evoke",
  "ewers", "exact", "exalt", "exams", "excel", "exec", "execs", "exert", "exile", "exist",
  "exits", "expat", "expel", "expos", "extol", "extra", "exude", "exult", "exurb", "eying",
  "eyrie",

  // F
  "fable", "faced", "facer", "faces", "facet", "facia", "facts", "faddy", "faded", "fader",
  "fades", "fadge", "fados", "faena", "faery", "faff", "faffs", "fagin", "fagot", "fails",
  "faint", "fairs", "fairy", "faith", "faked", "faker", "fakes", "fakir", "falls", "false",
  "famed", "fames", "fancy", "fanes", "fangs", "fanos", "fanny", "fanon", "fanos", "fards",
  "fared", "farer", "fares", "farms", "faros", "farts", "fated", "fates", "fatly", "fatso",
  "fatty", "fatwa", "faugh", "fault", "fauna", "fauns", "fauve", "favor", "favus", "fawns",
  "fawny", "faxed", "faxes", "fazed", "fazes", "fears", "feast", "feats", "feaze", "fecal",
  "feces", "feeds", "feels", "feeze", "feign", "feint", "feist", "felid", "fells", "felly",
  "felon", "felts", "femes", "femme", "femur", "fence", "fends", "fenny", "feods", "feoff",
  "feral", "ferly", "fermi", "ferns", "ferny", "ferry", "fests", "fetal", "fetas", "fetch",
  "feted", "fetes", "fetid", "fetor", "fetus", "feuar", "feuds", "fever", "fewer", "feyer",
  "fezes", "fiars", "fiats", "fiber", "fibre", "fices", "fiche", "fichu", "ficin", "ficus",
  "fidos", "field", "fiefs", "fiend", "fiery", "fifed", "fifer", "fifes", "fifth", "fifty",
  "fight", "filar", "filch", "filed", "filer", "files", "filet", "fills", "filly", "filmi",
  "films", "filmy", "filth", "filum", "final", "finch", "finds", "fined", "finer", "fines",
  "finis", "finks", "finny", "finos", "fiord", "fired", "firer", "fires", "firms", "first",
  "firth", "fishy", "fists", "fitly", "fives", "fixed", "fixer", "fixes", "fixit", "fizzy",
  "fjeld", "fjord", "flabs", "flack", "flags", "flail", "flair", "flake", "flaks", "flaky",
  "flame", "flams", "flamy", "flank", "flans", "flaps", "flare", "flash", "flask", "flats",
  "flawn", "flaws", "flawy", "flays", "fleam", "fleas", "fleck", "flees", "fleet", "flesh",
  "flews", "flick", "flics", "flied", "flier", "flies", "fling", "flint", "flips", "flirt",
  "flits", "float", "flock", "flogs", "flong", "flood", "floor", "flops", "flora", "floss",
  "flota", "flour", "flout", "flown", "flows", "flubs", "flued", "flues", "fluff", "fluid",
  "fluke", "fluky", "flume", "flump", "flung", "flunk", "fluor", "flush", "flute", "fluty",
  "fluyt", "flyby", "flyer", "foals", "foams", "foamy", "focal", "focus", "fogey", "foggy",
  "fogie", "fohns", "foils", "foist", "folds", "folia", "folio", "folks", "folksy", "folky",
  "folly", "fonda", "fonds", "fondu", "fonts", "foods", "fools", "foots", "footy", "foram",
  "foray", "forbs", "force", "fords", "fores", "forex", "forge", "forgo", "forks", "forky",
  "forms", "fornix", "forte", "forth", "forts", "forty", "forum", "forwhy", "fossa", "fosse",
  "fouls", "found", "fount", "fours", "fovea", "fowls", "foxed", "foxes", "foyer", "frags",
  "frail", "frame", "franc", "frank", "fraps", "frass", "frats", "fraud", "frays", "freak",
  "freed", "freer", "frees", "fremd", "frena", "frere", "fresh", "frets", "friar", "fried",
  "frier", "fries", "frill", "frise", "frisk", "frith", "frits", "fritz", "frizz", "frock",
  "frogs", "frond", "frons", "front", "frore", "frosh", "frost", "froth", "frown", "frows",
  "frowy", "froze", "frugs", "fruit", "frump", "frush", "fryer", "fubsy", "fucks", "fucus",
  "fudge", "fudgy", "fuels", "fugal", "fuggy", "fugio", "fugle", "fugue", "fully", "fumed",
  "fumer", "fumes", "fumet", "fundi", "funds", "funky", "funny", "fural", "furan", "furls",
  "furor", "furry", "furze", "furzy", "fused", "fusee", "fusel", "fuses", "fusil", "fussy",
  "fusty", "futon", "fuzed", "fuzee", "fuzes", "fuzil", "fuzzy", "fyces", "fykes", "fyttes",

  // G
  "gabby", "gable", "gaddi", "gaffe", "gaffs", "gaged", "gager", "gages", "gaily", "gains",
  "gaits", "galah", "galas", "galax", "gales", "galls", "gally", "galop", "gamba", "gamed",
  "gamer", "games", "gamey", "gamic", "gamin", "gamma", "gammy", "gamps", "gamut", "ganev",
  "gangs", "ganja", "ganofs", "gaper", "gapes", "gappy", "garbs", "garni", "garth", "gases",
  "gasps", "gassy", "gated", "gater", "gates", "gator", "gauds", "gaudy", "gauge", "gault",
  "gaums", "gaunt", "gaurs", "gauss", "gauze", "gauzy", "gavel", "gavot", "gawks", "gawky",
  "gawps", "gayal", "gayer", "gayly", "gazed", "gazer", "gazes", "gazoo", "gears", "gecko",
  "geeks", "geeky", "geese", "geest", "gelds", "gelee", "gelid", "gelts", "gemmy", "gemot",
  "genes", "genet", "genic", "genie", "genii", "genip", "genoa", "genom", "genre", "genro",
  "gents", "genua", "genus", "geode", "geoid", "germs", "germy", "gesso", "geste", "gests",
  "getas", "getup", "ghast", "ghats", "ghaut", "ghazi", "ghees", "ghost", "ghoul", "ghyll",
  "giant", "gibed", "giber", "gibes", "giddy", "gifts", "gigas", "gighe", "gigot", "gigue",
  "gilds", "gills", "gilly", "gilts", "gimel", "gimme", "gimps", "gimpy", "ginks", "ginny",
  "gipon", "gipsy", "girds", "girls", "girly", "girns", "giron", "giros", "girsh", "girth",
  "girts", "gismo", "gists", "gites", "given", "giver", "gives", "gizmo", "glace", "glade",
  "glads", "glady", "glair", "glams", "gland", "glans", "glare", "glary", "glass", "glaur",
  "glaze", "glazy", "gleam", "glean", "gleba", "glebe", "gleed", "gleek", "gleet", "glees",
  "glegs", "gleys", "glial", "glias", "glide", "gliff", "glims", "glint", "glisk", "glits",
  "gloam", "gloat", "globe", "globs", "gloms", "gloom", "gloop", "glops", "glory", "gloss",
  "glost", "glove", "glows", "gloze", "glued", "gluer", "glues", "gluey", "glugs", "glume",
  "glums", "gluon", "glute", "glyph", "gnarl", "gnarr", "gnars", "gnash", "gnats", "gnawn",
  "gnaws", "gnome", "goads", "goafs", "goals", "goats", "goban", "gobos", "godet", "godly",
  "goers", "gofer", "gogos", "going", "golds", "golem", "golfs", "golly", "gombo", "gomer",
  "gonad", "gonef", "goner", "gongs", "gonia", "gonif", "gonks", "gonna", "gonof", "gonyf",
  "goods", "goody", "gooey", "goofs", "goofy", "googs", "gooks", "gooky", "goons", "goony",
  "goops", "goopy", "goose", "goosy", "gopik", "gorad", "gored", "gores", "gorge", "gorps",
  "gorse", "gorsy", "goths", "gouge", "gourd", "gouts", "gouty", "gowan", "gowds", "gowks",
  "gowns", "goyim", "grabs", "grace", "grade", "grads", "graff", "graft", "grail", "grain",
  "grams", "grana", "grand", "grans", "grant", "grape", "graph", "grapy", "grasp", "grass",
  "grate", "grave", "gravy", "grays", "graze", "great", "grebe", "greed", "greek", "green",
  "grees", "greet", "grego", "greys", "grids", "grief", "grift", "grigs", "grill", "grime",
  "grimy", "grind", "grins", "griot", "gripe", "grips", "gript", "gripy", "grist", "grith",
  "grits", "grivet", "grody", "grogs", "groin", "groks", "groma", "groom", "grope", "gross",
  "grots", "group", "grout", "grove", "grovy", "growl", "grown", "grows", "grrls", "gruel",
  "gruff", "grume", "grump", "grumpy", "grunt", "grypt", "guana", "guano", "guans", "guard",
  "guars", "guava", "gucks", "gudes", "guess", "guest", "guffs", "guide", "guidos", "guids",
  "guild", "guile", "guilt", "guiro", "gulch", "guldens", "gules", "gulfs", "gulfy", "gulls",
  "gully", "gulps", "gulpy", "gumbo", "gumma", "gummy", "gunks", "gunny", "guppy", "gurge",
  "gurgle", "gurns", "gurry", "gursh", "gushy", "gusto", "gusts", "gusty", "gutsy", "gutta",
  "gutty", "guyed", "guyot", "gymen", "gypped", "gyppo", "gyral", "gyred", "gyres", "gyros",
  "gyved", "gyves",

  // H
  "habit", "hacek", "hacks", "hadal", "haded", "hades", "hadji", "hadst", "haems", "hafis",
  "hafiz", "hafts", "haggis", "hagia", "haika", "haiku", "hails", "haint", "hairs", "hairy",
  "hajes", "hajis", "hajji", "haled", "haler", "hales", "halls", "halms", "halon", "halos",
  "halts", "halva", "halve", "halwa", "hamal", "hames", "hammy", "hands", "handy", "hangs",
  "hanks", "hanky", "hansa", "hanse", "haole", "haply", "happy", "hards", "hardy", "hared",
  "harem", "hares", "harks", "harls", "harms", "harps", "harpy", "harry", "harsh", "harts",
  "haste", "hasta", "hasty", "hatch", "hated", "hater", "hates", "haugh", "haulm", "hauls",
  "haunt", "haute", "haven", "haver", "haves", "havoc", "hawed", "hawks", "haws", "hayed",
  "hayer", "hazan", "hazed", "hazel", "hazer", "hazes", "heads", "heady", "heald", "heals",
  "heaps", "heapy", "heard", "hears", "heart", "heath", "heats", "heave", "heavy", "hebes",
  "heder", "hedge", "hedgy", "heeds", "heels", "heeze", "hefts", "hefty", "heigh", "heils",
  "heirs", "heist", "helices", "helix", "hello", "hells", "helms", "helos", "helot", "helps",
  "helve", "hemes", "hemic", "hemin", "hemps", "hempy", "hence", "henge", "henna", "henry",
  "hents", "herbs", "herby", "herds", "heres", "heron", "herry", "hertz", "hests", "heths",
  "hewed", "hewer", "hexad", "hexed", "hexer", "hexes", "hexyl", "hicks", "hided", "hider",
  "hides", "highs", "hight", "hijab", "hiked", "hiker", "hikes", "hilar", "hilla", "hills",
  "hilly", "hilts", "hilum", "hilus", "himbo", "hinds", "hinge", "hints", "hippy", "hired",
  "hirer", "hires", "hissy", "hists", "hitch", "hived", "hives", "hoagy", "hoard", "hoars",
  "hoary", "hobby", "hocks", "hocus", "hodad", "hoers", "hogan", "hoged", "hoist", "hoked",
  "hokes", "hokey", "hokum", "holds", "holed", "holes", "holey", "holts", "homed", "homer",
  "homes", "homey", "homie", "homos", "honan", "honda", "honed", "honer", "hones", "honey",
  "honks", "honky", "honor", "hooch", "hoods", "hoody", "hooey", "hoofs", "hooks", "hooky",
  "hooly", "hoops", "hoots", "hooty", "hoove", "hoped", "hoper", "hopes", "hoppy", "horah",
  "horal", "horas", "horde", "horns", "horny", "horse", "horst", "horsy", "hosed", "hosel",
  "hoser", "hoses", "hosey", "hosta", "hosts", "hotel", "hotly", "hound", "houri", "hours",
  "house", "hovel", "hover", "howdy", "howes", "howks", "howls", "hubby", "huffs", "huffy",
  "huger", "huggy", "hulas", "hulks", "hulky", "hullo", "hulls", "human", "humble", "humid",
  "humic", "humid", "humor", "humph", "humps", "humpy", "humus", "hunch", "hunks", "hunky",
  "hunts", "hurds", "hurls", "hurly", "hurry", "hurts", "husks", "husky", "hussy", "hutch",
  "huzza", "hydra", "hydro", "hyena", "hyenas", "hying", "hyman", "hymen", "hymns", "hyoid",
  "hyped", "hyper", "hypes", "hypha", "hypos", "hyrax", "hyson",

  // I
  "iambi", "iambs", "ibex", "ibis", "ibices", "ibrik", "iceberg", "icers", "iched", "iches",
  "icier", "icily", "icing", "icker", "icons", "ictus", "ideas", "idea", "ideal", "ideas",
  "idiom", "idiot", "idled", "idler", "idles", "idols", "idyll", "idyls", "iftar", "igged",
  "igloo", "ileal", "ileum", "ileus", "iliac", "ilial", "ilium", "iller", "image", "imago",
  "imams", "imbue", "imids", "imine", "imino", "immix", "imped", "impel", "impis", "imply",
  "impro", "inane", "inapt", "inarm", "inbox", "inbye", "incog", "incur", "incus", "index",
  "indie", "indol", "indow", "indri", "indue", "inept", "inert", "infer", "infix", "infos",
  "infra", "inged", "ingles", "ingot", "inion", "inked", "inker", "inkle", "inlay", "inlet",
  "inned", "inner", "inorb", "input", "inset", "inspan", "intel", "intend", "inter", "intro",
  "inure", "inurn", "invar", "iodic", "iodin", "ionic", "iotas", "irade", "irate", "irked",
  "iring", "irons", "irony", "isle", "isled", "isles", "islet", "issue", "isthmi", "itchy",
  "items", "ither", "ivied", "ivies", "ivory", "ixias", "ixnay", "ixtle", "izard", "izars",

  // J
  "jabot", "jacal", "jacks", "jacky", "jaded", "jades", "jager", "jaggs", "jaggy", "jagra",
  "jails", "jakes", "jalap", "jambe", "jambs", "james", "jammy", "janes", "japan", "japed",
  "japer", "japes", "jarls", "jarred", "jasmine", "jato", "jatos", "jauks", "jaunt", "jaunty",
  "jaups", "javas", "jawan", "jawed", "jazzy", "jeans", "jebel", "jeers", "jeeps", "jefes",
  "jehad", "jehus", "jelab", "jells", "jelly", "jemmy", "jenny", "jerid", "jerks", "jerky",
  "jests", "jesus", "jetes", "jeton", "jetty", "jewed", "jewel", "jibbs", "jibed", "jiber",
  "jibes", "jiffs", "jiffy", "jihad", "jills", "jilts", "jimmy", "jimpy", "jingo", "jinks",
  "jinni", "jinns", "jirga", "jissom", "jived", "jives", "jivey", "jnana", "jocko", "jocks",
  "joeys", "johns", "joins", "joint", "joist", "joked", "joker", "jokes", "jokey", "joles",
  "jolly", "jolts", "jolty", "jombs", "joram", "jorum", "joshes", "joust", "jouks", "joule",
  "jowar", "jowed", "jowls", "jowly", "joyed", "joyes", "judge", "judos", "jugal", "jugum",
  "juice", "juicy", "juked", "jukes", "julep", "jumbo", "jumpy", "junco", "junks", "junky",
  "junta", "junto", "jupes", "jupon", "jural", "jurat", "jurel", "juris", "juror", "justs",
  "jutes", "jutty",

  // K
  "kabar", "kabob", "kades", "kadis", "kafir", "kagus", "kaiak", "kails", "kains", "kaiser",
  "kakas", "kaki", "kakis", "kalam", "kales", "kalif", "kalpa", "kames", "kamik", "kanas",
  "kanji", "kapok", "kappa", "kaput", "karat", "karma", "karst", "karts", "kasha", "katas",
  "kathodes", "kava", "kayak", "kayos", "kazoo", "kebab", "kebar", "kebob", "kedge", "keefs",
  "keeks", "keels", "keens", "keeps", "kefir", "kelep", "kelim", "kelly", "kelp", "kelps",
  "kelpy", "kemps", "kempt", "kenaf", "kench", "kendo", "kenos", "kepis", "kerbs", "kerfs",
  "kerne", "kerns", "kerry", "ketch", "ketol", "kevel", "kevil", "keyed", "keyer", "khadi",
  "khafs", "khaki", "khans", "khaph", "kheth", "khoum", "kibei", "kibes", "kibla", "kicks",
  "kicky", "kiddo", "kiddy", "kiefs", "kiers", "kikes", "kilim", "kills", "kilns", "kilos",
  "kilts", "kilty", "kinas", "kinds", "kines", "kings", "kinin", "kinks", "kinky", "kinos",
  "kiosk", "kippa", "kippy", "kirks", "kirns", "kirsch", "kissy", "kited", "kiter", "kites",
  "kithe", "kiths", "kitty", "kivas", "kiwis", "klong", "kloof", "kluge", "klutz", "knack",
  "knaps", "knars", "knave", "knawe", "knead", "kneel", "knees", "knell", "knelt", "knife",
  "knish", "knits", "knobs", "knock", "knoll", "knops", "knosp", "knots", "knout", "known",
  "knows", "knurl", "knurs", "koala", "kobos", "kohls", "kohol", "koine", "kolas", "kombu",
  "konks", "kooks", "kooky", "kopek", "kophs", "kopje", "koppa", "koras", "korat", "kores",
  "korma", "korun", "kotos", "kotow", "kraal", "kraft", "krait", "kraut", "kreep", "krewe",
  "krill", "krona", "krone", "kroon", "krubi", "kudos", "kudus", "kudzu", "kugel", "kukri",
  "kulak", "kulas", "kulan", "kvass", "kvell", "kyack", "kyaks", "kyats", "kybos", "kylix",
  "kynd", "kyrie", "kytes", "kythe",

  // L
  "label", "labia", "labor", "laced", "lacer", "laces", "lacey", "lacks", "laddy", "laden",
  "lader", "lades", "ladle", "lager", "lahar", "laics", "laigh", "laird", "lairs", "laith",
  "laity", "laked", "laker", "lakes", "lakhs", "lamas", "lambs", "lamed", "lamer", "lames",
  "lamia", "lamps", "lanai", "lance", "lands", "lanes", "lanky", "lapel", "lapin", "lapis",
  "lapse", "larch", "lards", "lardy", "lared", "lares", "large", "largo", "larks", "larky",
  "larns", "larum", "larva", "lased", "laser", "lases", "lassi", "lasso", "lasts", "latch",
  "lated", "laten", "later", "latex", "lathe", "laths", "lathy", "latke", "latte", "lauan",
  "lauds", "laugh", "laura", "laved", "laver", "laves", "lavas", "lawed", "lawer", "lawns",
  "lawny", "laxer", "laxes", "layed", "layer", "layup", "lazar", "lazed", "lazes", "lazily",
  "leach", "leads", "leady", "leafs", "leafy", "leaks", "leaky", "leans", "leant", "leaps",
  "leapt", "learn", "leary", "lease", "leash", "least", "leave", "leavy", "leben", "ledge",
  "ledgy", "leech", "leeks", "leers", "leery", "lefts", "lefty", "legal", "leger", "leges",
  "leggy", "legit", "lehrs", "lehua", "lemma", "lemon", "lemur", "lends", "lento", "leone",
  "leper", "lepta", "levee", "level", "lever", "levin", "lexes", "lexis", "lezzy", "liana",
  "liane", "liang", "liars", "libel", "liber", "libra", "libri", "licks", "licit", "lidar",
  "lidos", "liefs", "liege", "liens", "liers", "lieus", "lieve", "lifer", "lifes", "lifts",
  "ligan", "liger", "light", "liked", "liken", "liker", "likes", "lilac", "lills", "lilts",
  "limas", "limba", "limbo", "limbs", "limby", "limed", "limen", "limes", "limey", "limit",
  "limns", "limos", "limps", "limpa", "lindy", "lined", "linen", "liner", "lines", "liney",
  "lings", "lingy", "lined", "linin", "links", "linky", "linns", "linty", "lions", "lipid",
  "lippy", "lirot", "lisle", "lisps", "lists", "litas", "lited", "liter", "lites", "lithe",
  "litho", "lithy", "litre", "litten", "lived", "liven", "liver", "lives", "livid", "livre",
  "llama", "llano", "loach", "loads", "loafs", "loams", "loamy", "loans", "loath", "lobar",
  "lobby", "lobed", "lobes", "lobos", "local", "locks", "locos", "locum", "locus", "loden",
  "lodes", "lodge", "loess", "lofts", "lofty", "logan", "loges", "loggy", "logia", "logic",
  "logon", "logos", "loins", "lolly", "lone", "loner", "longe", "longs", "looed", "looey",
  "loofa", "loofs", "looie", "looks", "looms", "loons", "loony", "loops", "loopy", "loose",
  "loots", "loped", "loper", "lopes", "loppy", "lords", "lores", "loris", "lorry", "losel",
  "loser", "loses", "lossy", "lotas", "lotic", "lotos", "lotto", "lotus", "louie", "lough",
  "louie", "louis", "loupe", "loups", "lours", "loury", "louse", "lousy", "louts", "lovat",
  "loved", "lover", "loves", "lowed", "lower", "lowes", "lowly", "loxes", "luaus", "lubed",
  "lubes", "luces", "lucid", "lucks", "lucky", "lucre", "ludes", "ludic", "ludos", "luffa",
  "luffs", "luges", "lulls", "lulus", "lumen", "lumps", "lumpy", "lunar", "lunas", "lunch",
  "lunes", "lunet", "lunge", "lungi", "lungs", "lunks", "lunts", "lupin", "lupus", "lurch",
  "lured", "lurer", "lures", "lurid", "lurks", "lusts", "lusty", "lusus", "lutea", "luted",
  "lutes", "luxes", "lwei", "lyard", "lyart", "lyase", "lycee", "lycra", "lying", "lymph",
  "lynch", "lynxes", "lyres", "lyric", "lysed", "lyses", "lysin", "lysis", "lyssa", "lythe",

  // M
  "maced", "macer", "maces", "machs", "macho", "macks", "macle", "macro", "madam", "madly",
  "madre", "mafia", "mafic", "magic", "magma", "magot", "magus", "mahoe", "maids", "maile",
  "mails", "maims", "mains", "maire", "mairs", "maize", "major", "makar", "maker", "makes",
  "malar", "males", "malls", "malms", "malmy", "malts", "malty", "mamas", "mambo", "mamey",
  "mamie", "mamma", "mammo", "mammy", "manas", "maned", "manes", "manga", "mange", "mango",
  "mangy", "mania", "manic", "manly", "manna", "manor", "manos", "manse", "manta", "manus",
  "maple", "maqui", "marcs", "mares", "marge", "maria", "marka", "marks", "marls", "marly",
  "marry", "marse", "marsh", "marts", "marvy", "mascon", "maser", "mashy", "masks", "mason",
  "masse", "masts", "masty", "match", "mated", "mater", "mates", "matey", "matin", "matte",
  "matts", "matza", "matzo", "mauds", "mauls", "maund", "mauts", "mauve", "maven", "mavin",
  "mavis", "mawed", "maxed", "maxes", "maxim", "maxis", "mayan", "mayas", "maybe", "mayed",
  "mayor", "mazed", "mazer", "mazes", "mbira", "meads", "meals", "mealy", "means", "meant",
  "meany", "meats", "meaty", "mecca", "medal", "media", "medic", "medii", "medusa", "meeds",
  "meets", "meiny", "melba", "melds", "melee", "mells", "melon", "melts", "memes", "memos",
  "menad", "mends", "mensa", "mense", "menta", "mento", "menus", "meows", "mercs", "mercy",
  "merde", "merer", "meres", "merge", "merit", "merks", "merles", "merlon", "merry", "meshes",
  "mesic", "meson", "messes", "messy", "metal", "meted", "meter", "metes", "meths", "metic",
  "metol", "metre", "metro", "mewed", "mewls", "mezes", "miaow", "miasm", "miaul", "micas",
  "miche", "micks", "micra", "micro", "middy", "midge", "midis", "midst", "miens", "miffs",
  "miffy", "might", "miked", "mikes", "milch", "milds", "miler", "miles", "milks", "milky",
  "mills", "milos", "milpa", "milts", "milty", "mimed", "mimeo", "mimer", "mimes", "mimic",
  "minae", "minar", "minas", "mince", "mincy", "minds", "mined", "miner", "mines", "mings",
  "minim", "minis", "minke", "minks", "minny", "minor", "minty", "minus", "mired", "mires",
  "mirin", "mirks", "mirky", "mirth", "mirzas", "misdo", "miser", "mises", "misos", "missy",
  "mists", "misty", "miter", "mites", "mitis", "mitre", "mitts", "mixed", "mixer", "mixes",
  "mixup", "mizen", "moans", "moats", "mocha", "mocks", "modal", "model", "modem", "modes",
  "modus", "moggy", "mohel", "mohur", "moils", "mojos", "molal", "molar", "molas", "molds",
  "moldy", "moles", "molly", "molto", "molts", "molys", "momma", "mommy", "momus", "monad",
  "monas", "monde", "mondo", "money", "mongo", "monic", "monie", "monks", "monos", "monte",
  "month", "mooch", "moods", "moody", "mooed", "moola", "mools", "moons", "moony", "moors",
  "moose", "moots", "moped", "moper", "mopes", "mopey", "morae", "moral", "moras", "moray",
  "morel", "mores", "moria", "morns", "moron", "morph", "morro", "morse", "morts", "mosey",
  "mosks", "mosso", "mossy", "moste", "moths", "mothy", "motif", "motor", "motte", "motto",
  "motts", "mouch", "mould", "moult", "mound", "mount", "mourn", "mouse", "mousy", "mouth",
  "moved", "mover", "moves", "movie", "mowed", "mower", "moxas", "moxie", "muced", "mucid",
  "mucin", "mucky", "mucor", "mucro", "mucus", "muddy", "mudge", "mudras", "muffs", "mufti",
  "muggs", "muggy", "muhly", "mujik", "mulch", "mulct", "muled", "mules", "muley", "mulla",
  "mulls", "molly", "mumbo", "mumms", "mummy", "mumps", "munch", "mungo", "muons", "mural",
  "muras", "mured", "mures", "murex", "murid", "murks", "murky", "murls", "murly", "murre",
  "murrs", "murry", "murva", "mused", "muser", "muses", "mushy", "musks", "musky", "musos",
  "musse", "mussy", "musts", "musty", "muted", "muter", "mutes", "mutts", "muzzy", "mynas",
  "mynah", "myoma", "myope", "myopy", "myrrh", "myths", "mythy",

  // N
  "nabes", "nabob", "nache", "nacre", "nadas", "nadir", "naevi", "naiad", "naifs", "nails",
  "naive", "naked", "naled", "named", "namer", "names", "nanas", "nance", "nanny", "nanos",
  "napes", "nappa", "nappe", "nappy", "narco", "narcs", "nards", "nares", "naric", "nariss",
  "nasal", "nasty", "natal", "natch", "nates", "natty", "naval", "navar", "navel", "naves",
  "navvy", "nawab", "nazes", "nazis", "neaps", "nears", "neath", "neats", "necks", "neddy",
  "needs", "needy", "neeps", "negus", "neifs", "neigh", "nelly", "nemas", "nenes", "neons",
  "nerds", "nerdy", "nerol", "nerts", "nervy", "nerve", "nests", "netop", "netts", "netty",
  "neuks", "neume", "neums", "never", "neves", "nevus", "newel", "newer", "newie", "newly",
  "newsy", "newts", "nexts", "nexus", "ngwee", "nicer", "niche", "nicks", "niece", "nieve",
  "nifty", "nighs", "night", "nihil", "nilly", "nimbi", "nines", "ninny", "ninon", "ninth",
  "nipas", "nippy", "nisei", "niter", "nitid", "niton", "nitre", "nitro", "nitty", "nival",
  "nixed", "nixes", "nixie", "nizam", "nobby", "noble", "nobly", "nocks", "nodal", "noddy",
  "nodes", "nodus", "noels", "noggin", "nohow", "noils", "noily", "noirs", "noise", "noisy",
  "nolos", "nomad", "nomas", "nomen", "nomes", "nomoi", "nomos", "nonas", "nones", "nonet",
  "nooks", "nooky", "noons", "noose", "noria", "noris", "norms", "north", "nosed", "noser",
  "noses", "notal", "notch", "noted", "noter", "notes", "nouns", "novae", "novas", "novel",
  "noway", "nowts", "nubby", "nubia", "nucha", "nudes", "nudge", "nudie", "nudism", "nukes",
  "nullah", "nulls", "numbs", "numen", "nurd", "nurds", "nurls", "nurse", "nutso", "nutsy",
  "nutty", "nyala", "nylon", "nymph",

  // O
  "oaken", "oakum", "oared", "oases", "oasis", "oasts", "oaten", "oater", "oaths", "oaves",
  "obeah", "obeli", "obese", "obeys", "obias", "obits", "objet", "oboes", "obole", "oboli",
  "obols", "occur", "ocean", "ocher", "oches", "ochre", "ochry", "ocker", "ockers", "ocrea",
  "octad", "octal", "octan", "octet", "octyl", "oculi", "odder", "oddly", "odeon", "odeum",
  "odism", "odist", "odium", "odors", "odour", "odyle", "odyls", "ofays", "offal", "offed",
  "offer", "often", "ofter", "ogams", "ogees", "ogham", "ogive", "ogled", "ogler", "ogles",
  "ogres", "ohias", "ohing", "ohmic", "oiled", "oiler", "oinks", "okays", "okehs", "okras",
  "olden", "older", "oldie", "oleic", "olein", "oleos", "oleum", "olios", "olive", "ollas",
  "ology", "omasa", "omber", "ombre", "ombus", "omega", "omens", "omers", "omits", "oncet",
  "onery", "onion", "onium", "onlay", "onset", "ontic", "oohed", "oomph", "oozed", "oozes",
  "opahs", "opals", "opens", "opera", "opine", "oping", "opium", "opted", "optic", "orals",
  "orang", "orate", "orbed", "orbit", "orcas", "orcin", "order", "ordos", "oread", "organ",
  "ormer", "ornate", "ornis", "orris", "orzo", "osier", "ossia", "ostia", "other", "ottar",
  "otter", "ottos", "ought", "ouija", "ounce", "ousts", "outdo", "outed", "outer", "outre",
  "ouzel", "ouzos", "ovals", "ovary", "ovate", "ovens", "overs", "overt", "ovine", "ovoid",
  "ovoli", "ovolo", "ovule", "owers", "owies", "owing", "owlet", "owned", "owner", "oxbow",
  "oxers", "oxide", "oxids", "oxime", "oxims", "oxlip", "oxter", "oyers", "ozone",

  // P
  "paced", "pacer", "paces", "pacey", "pacha", "packs", "pacta", "pacts", "padded", "paddy",
  "padis", "padle", "padre", "padri", "padrone", "paean", "paeon", "pagan", "paged", "pager",
  "pages", "pails", "pains", "paint", "pairs", "paisa", "paise", "paled", "paler", "pales",
  "palet", "palis", "palls", "pally", "palms", "palmy", "palpi", "palps", "palsa", "palsy",
  "pampa", "panda", "pands", "paned", "panel", "panes", "pangs", "panic", "panini", "panko",
  "pansy", "panto", "pants", "panty", "papal", "papas", "papaw", "paper", "pappa", "pappi",
  "pappy", "parae", "paras", "parch", "pardi", "pardy", "pared", "parer", "pares", "pareu",
  "parge", "parka", "parks", "parky", "parle", "parol", "parrot", "parry", "parse", "parsi",
  "parts", "party", "parvo", "paseo", "pases", "pasha", "pashm", "passe", "pasta", "paste",
  "pasts", "pasty", "patch", "pated", "paten", "pater", "pates", "paths", "patio", "patly",
  "patsy", "patty", "paunch", "pause", "paved", "paver", "paves", "pawed", "pawer", "pawls",
  "pawns", "paxes", "payed", "payee", "payer", "peace", "peach", "peage", "peags", "peaks",
  "peaky", "peals", "peans", "pearl", "pears", "peart", "pease", "peats", "peaty", "peavy",
  "pecan", "pechs", "pecks", "pedal", "pedes", "pedis", "pedro", "peeks", "peeled", "peels",
  "peens", "peeps", "peers", "peery", "peeve", "peewee", "pegbox", "pekan", "pekes", "pekin",
  "pekoe", "peles", "pelfs", "pelts", "penal", "pence", "pends", "penes", "pengo", "penis",
  "penna", "penne", "penni", "penny", "peons", "peony", "pepla", "pepos", "peppy", "pepsin",
  "perch", "perdu", "perdy", "perea", "peril", "peris", "perks", "perky", "perms", "perp",
  "perry", "perse", "pesky", "pesos", "pests", "petal", "peter", "petit", "petti", "petto",
  "petty", "pewee", "pewit", "phage", "phase", "phat", "phial", "phlox", "phone", "phons",
  "phony", "photo", "photog", "phots", "phylum", "phyla", "physic", "piano", "pians", "pibal",
  "pical", "picas", "picks", "picky", "picot", "picus", "piece", "pieds", "piers", "pieta",
  "pietas", "piety", "piggy", "pighs", "pigmy", "piing", "piked", "piker", "pikes", "pilaf",
  "pilar", "pilau", "pilaw", "piled", "piler", "piles", "pilis", "pills", "pilon", "pilot",
  "pilus", "pimas", "pimps", "pinas", "pinch", "pined", "pines", "piney", "pings", "pinko",
  "pinks", "pinky", "pinna", "pinny", "pinon", "pinot", "pinta", "pinto", "pints", "pinup",
  "pions", "pious", "piped", "piper", "pipes", "pipet", "pique", "pirog", "pirns", "pisco",
  "pised", "pises", "pissy", "pitas", "pitch", "piths", "pithy", "piton", "pivot", "pixel",
  "pixes", "pixie", "pizza", "place", "plack", "plage", "plaid", "plain", "plait", "plane",
  "plank", "plans", "plant", "plash", "plasm", "plate", "plats", "playa", "plays", "plaza",
  "plead", "pleas", "pleat", "plebs", "plena", "pleura", "plied", "plier", "plies", "plink",
  "plods", "plops", "plots", "plows", "ploys", "pluck", "plugs", "plumb", "plume", "plump",
  "plums", "plumy", "plunk", "pluse", "plush", "plyer", "poach", "pocks", "pocky", "podgy",
  "podia", "poems", "poesy", "poets", "pogey", "pogos", "poilu", "point", "poise", "poked",
  "poker", "pokes", "pokey", "polar", "poled", "poler", "poles", "poley", "polio", "polis",
  "polka", "polks", "polls", "polos", "polyp", "polys", "pomes", "pommy", "ponce", "poncho",
  "pondoks", "ponds", "pones", "pongs", "ponks", "pooch", "poofs", "poofy", "poohs", "pools",
  "poons", "poops", "poori", "poorly", "popes", "poppa", "poppy", "porch", "pored", "porer",
  "pores", "porgy", "porks", "porky", "porno", "porns", "porny", "porta", "ports", "posed",
  "poser", "poses", "posey", "posh", "posho", "posit", "posse", "posts", "potsy", "potto",
  "potty", "pouch", "poufs", "pouffe", "pouffs", "poult", "pound", "pours", "pouts", "pouty",
  "power", "poxed", "poxes", "prams", "prang", "prank", "praos", "prase", "prate", "prats",
  "praus", "prawn", "prays", "preen", "prees", "prepay", "preppy", "preps", "presa", "prese",
  "press", "prest", "prexy", "preys", "price", "prick", "pricy", "pride", "pried", "prier",
  "pries", "prigs", "prill", "prima", "prime", "primi", "primo", "primp", "prims", "prink",
  "print", "prion", "prior", "prise", "prism", "priss", "privy", "prize", "proas", "probe",
  "prods", "proem", "profs", "progs", "prole", "promo", "proms", "prone", "prong", "proof",
  "props", "prose", "proso", "pross", "prost", "prosy", "proud", "prove", "prowl", "prows",
  "proxy", "prude", "prune", "pryer", "psalm", "pseud", "psoas", "psych", "pubes", "pubic",
  "pubis", "pucks", "puddy", "pudge", "pudgy", "puffs", "puffy", "puggy", "pugils", "puked",
  "pukes", "puker", "pukka", "puled", "puler", "pules", "pulik", "pulis", "pulls", "pulps",
  "pulpy", "pulse", "pumas", "pumps", "punas", "punch", "punji", "punks", "punky", "punny",
  "punts", "punty", "pupae", "pupal", "pupas", "pupil", "puppy", "puree", "purer", "purge",
  "purin", "purls", "purrs", "purse", "pursy", "pushy", "pussy", "putts", "putti", "putto",
  "putty", "puzzle", "pygmy", "pyins", "pylon", "pyoid", "pyran", "pyres", "pyric", "pyrol",
  "pyxes", "pyxie", "pyxis",

  // Q
  "qadis", "qaids", "qanat", "qophs", "quack", "quads", "quaff", "quags", "quail", "quais",
  "quake", "quaky", "qualm", "quals", "quango", "quant", "quark", "quart", "quash", "quasi",
  "quass", "quate", "quays", "queen", "queer", "quell", "query", "quest", "queue", "quick",
  "quids", "quiet", "quiff", "quill", "quilt", "quins", "quint", "quips", "quipu", "quire",
  "quirk", "quirt", "quist", "quite", "quito", "quits", "quods", "quoin", "quoit", "quoll",
  "quota", "quote", "quoth",

  // R
  "rabbi", "rabid", "raced", "racer", "races", "racks", "racon", "radar", "radii", "radio",
  "radon", "rafts", "raged", "rager", "rages", "ragis", "raids", "rails", "rains", "rainy",
  "raise", "rajah", "rajas", "raked", "raker", "rakes", "rakis", "rally", "ralph", "ramen",
  "ramet", "ramie", "ramps", "ramus", "ranch", "rands", "randy", "ranee", "range", "rangy",
  "ranid", "ranis", "ranks", "rants", "raped", "raper", "rapes", "rapid", "rared", "rares",
  "rasps", "raspy", "ratan", "ratch", "rated", "rater", "rates", "ratha", "ratio", "ratos",
  "ratty", "raved", "ravel", "raven", "raver", "raves", "ravin", "rawer", "rawly", "rayah",
  "rayas", "rayed", "rayon", "razed", "razee", "razer", "razes", "razor", "reach", "react",
  "reads", "ready", "realm", "reals", "reams", "reaps", "rears", "reata", "rebab", "rebar",
  "rebbe", "rebec", "rebel", "rebid", "rebop", "rebus", "rebut", "recap", "recce", "recks",
  "recon", "recta", "recti", "recto", "recur", "redan", "redds", "reded", "redes", "redia",
  "redid", "redip", "redo", "redon", "redos", "redox", "redry", "redux", "redye", "reedy",
  "reefs", "reeks", "reeky", "reels", "reens", "reest", "reeve", "refed", "refer", "refit",
  "refix", "refly", "refry", "regal", "reges", "regna", "rehab", "rehem", "reify", "reign",
  "reins", "reked", "rekey", "relax", "relay", "relet", "relic", "relit", "remap", "remen",
  "remet", "remex", "remit", "remix", "renal", "rends", "renew", "renig", "rente", "rents",
  "reoil", "repay", "repel", "repin", "reply", "repos", "repot", "repps", "repro", "reran",
  "rerun", "resaw", "resay", "resee", "reset", "resew", "resh", "resid", "resin", "resod",
  "rests", "retag", "retax", "retch", "retem", "retia", "retie", "retro", "retry", "reuse",
  "revel", "revs", "revue", "rezes", "rhea", "rheas", "rheme", "rheum", "rhino", "rhomb",
  "rhumb", "rhyme", "rials", "riant", "riata", "ribby", "riced", "ricer", "rices", "ricin",
  "ricks", "rider", "rides", "ridge", "ridgy", "riels", "rifer", "riffs", "rifle", "rifts",
  "right", "rigid", "rigor", "riled", "riles", "riley", "rille", "rills", "rimed", "rimer",
  "rimes", "rinds", "rings", "rinks", "rinse", "rioja", "riots", "riped", "ripen", "riper",
  "ripes", "risen", "riser", "rises", "risks", "risky", "rites", "ritzy", "rival", "rived",
  "riven", "river", "rives", "rivet", "riyal", "roach", "roads", "roams", "roans", "roars",
  "roary", "roast", "robed", "robes", "robin", "roble", "robot", "rocks", "rocky", "rodeo",
  "roger", "rogue", "roguy", "roils", "roily", "roles", "rolls", "roman", "romeo", "romps",
  "rondo", "roofs", "rooks", "rooky", "rooms", "roomy", "roost", "roots", "rooty", "roped",
  "roper", "ropes", "ropey", "roque", "rosed", "roses", "roset", "roshi", "rosin", "rotas",
  "rotch", "roted", "rotes", "rotis", "rotls", "rotor", "rotos", "rouen", "rough", "round",
  "roups", "roupy", "rouse", "roust", "route", "routs", "roved", "rover", "roves", "rowan",
  "rowdy", "rowed", "rowel", "rower", "rowth", "royal", "ruana", "rubato", "rubel", "rubes",
  "rubin", "ruble", "ruche", "rucks", "ruddy", "ruder", "rudes", "ruers", "ruffe", "ruffs",
  "rufus", "rugae", "rugal", "rugby", "ruing", "ruins", "ruled", "ruler", "rules", "rummy",
  "rumor", "rumpy", "rumps", "runed", "runes", "rungs", "runic", "runny", "runts", "runty",
  "rupee", "rural", "ruses", "rushy", "rusks", "russet", "rusts", "rusty", "ruths", "rutin",
  "rutty", "ryots", "rynds",

  // S
  "sabal", "saber", "sabes", "sabin", "sabir", "sable", "sabot", "sabra", "sabre", "sacks",
  "sadhe", "sadhu", "sadly", "sados", "sadza", "safer", "safes", "sagas", "sager", "sages",
  "saggy", "sagos", "sagum", "sahib", "saice", "saids", "saiga", "sails", "saith", "sajou",
  "saker", "sakes", "salad", "salal", "salep", "sales", "salic", "salix", "sally", "salmi",
  "salol", "salon", "salpa", "salps", "salsa", "salse", "salts", "salty", "salud", "salve",
  "salvo", "samas", "samba", "sambo", "samek", "samen", "samps", "sands", "sandy", "saned",
  "saner", "sanes", "sangh", "sango", "sanko", "saned", "sansa", "santo", "sapor", "sappy",
  "sarape", "sarde", "sards", "sarge", "sargo", "saris", "sarki", "sarks", "sarky", "sarod",
  "saros", "sasin", "sasses", "sassy", "satay", "sated", "satem", "sates", "satin", "satis",
  "satyr", "sauce", "sauch", "saugh", "sauls", "sault", "sauna", "saury", "saute", "saved",
  "saver", "saves", "savin", "savor", "savoy", "savvy", "sawed", "sawer", "saxes", "sayer",
  "sayid", "sayyid", "scabs", "scads", "scags", "scald", "scale", "scall", "scalp", "scaly",
  "scamp", "scams", "scans", "scant", "scape", "scare", "scarf", "scarp", "scars", "scart",
  "scary", "scats", "scatt", "scaup", "scaur", "scena", "scend", "scene", "scent", "schav",
  "schmo", "schul", "schwa", "scion", "sclera", "scoff", "scold", "scone", "scoop", "scoot",
  "scope", "scops", "score", "scorn", "scots", "scour", "scout", "scowl", "scows", "scrag",
  "scram", "scrap", "scree", "screw", "scrim", "scrip", "scrod", "scrub", "scrum", "scuba",
  "scudi", "scudo", "scuds", "scuff", "sculk", "scull", "sculp", "scups", "scurf", "scuse",
  "scuta", "scute", "scuts", "scutum", "sebums", "secco", "sects", "sedan", "seder", "sedge",
  "sedgy", "sedum", "seeds", "seedy", "seeks", "seels", "seely", "seems", "seeps", "seepy",
  "seers", "segno", "segos", "segue", "seine", "seise", "seism", "seize", "selah", "selfs",
  "sells", "selva", "semes", "semis", "senas", "sends", "sengi", "senor", "senna", "sense",
  "sensi", "sente", "senti", "sepal", "sepia", "sepic", "sepoy", "septa", "septs", "sequel",
  "serac", "serai", "seral", "sered", "serer", "seres", "serfs", "serge", "serif", "serin",
  "sermon", "serow", "serry", "serum", "serve", "servo", "sesh", "setal", "seton", "setup",
  "seven", "sever", "sewan", "sewar", "sewed", "sewer", "sexed", "sexer", "sexes", "sexto",
  "sexts", "shack", "shade", "shads", "shady", "shaft", "shags", "shahs", "shake", "shako",
  "shaky", "shale", "shall", "shalt", "shaly", "shame", "shams", "shank", "shape", "shaps",
  "shard", "share", "shark", "sharn", "sharp", "shave", "shawl", "shawm", "shays", "sheaf",
  "sheal", "shear", "sheas", "sheds", "sheen", "sheep", "sheer", "sheet", "sheik", "shelf",
  "shell", "sherd", "shews", "shied", "shiel", "shier", "shies", "shift", "shill", "shily",
  "shims", "shine", "shins", "shiny", "ships", "shire", "shirk", "shirr", "shirt", "shist",
  "shits", "shiva", "shive", "shivs", "shlep", "shoal", "shoat", "shock", "shoed", "shoer",
  "shoes", "shogs", "shoji", "shone", "shoo", "shook", "shoos", "shoot", "shops", "shore",
  "shorl", "shorn", "short", "shote", "shots", "shott", "shout", "shove", "shown", "shows",
  "showy", "shoyu", "shred", "shrew", "shris", "shrub", "shrug", "shuck", "shuln", "shuls",
  "shuns", "shunt", "shush", "shut", "shuts", "shyer", "shyly", "sibyl", "sices", "sicko",
  "sicks", "sided", "sider", "sides", "sidhe", "sidle", "siege", "sieur", "sieve", "sifts",
  "sighs", "sight", "sigil", "sigma", "signa", "signed", "signs", "silds", "silex", "silks",
  "silky", "sills", "silly", "silos", "silts", "silty", "silva", "simar", "simas", "simis",
  "simps", "since", "sines", "sinew", "singe", "sings", "sinhs", "sinks", "sinus", "siped",
  "sipes", "sired", "siree", "siren", "sires", "sirih", "siris", "sirra", "sirup", "sisal",
  "sises", "sissy", "siste", "sitar", "sited", "sites", "sixes", "sixmo", "sixte", "sixth",
  "sixty", "sized", "sizer", "sizes", "skags", "skald", "skank", "skate", "skats", "skean",
  "skeed", "skees", "skegs", "skein", "skelm", "skelp", "skene", "skeps", "skerry", "sketch",
  "skews", "skids", "skied", "skier", "skies", "skiff", "skill", "skimo", "skimp", "skims",
  "skink", "skins", "skint", "skios", "skips", "skirl", "skirr", "skirt", "skis", "skite",
  "skits", "skive", "skoal", "skols", "skuas", "skulk", "skull", "skunk", "slabs", "slack",
  "slags", "slain", "slake", "slams", "slang", "slank", "slant", "slaps", "slash", "slate",
  "slats", "slatt", "slaty", "slave", "slaws", "slays", "sleds", "sleek", "sleep", "sleet",
  "slept", "slews", "slice", "slick", "slide", "slier", "slime", "slims", "slimy", "sling",
  "slink", "slipe", "slips", "slipt", "slits", "slobs", "sloes", "slogs", "sloid", "slojd",
  "slomo", "sloop", "slope", "slops", "slosh", "sloth", "slots", "slows", "sloyd", "slubs",
  "slue", "slued", "slues", "slugs", "slums", "slump", "slung", "slunk", "slurb", "slurp",
  "slurs", "slush", "sluts", "slyer", "slyly", "slype", "smack", "small", "smalt", "smarm",
  "smart", "smash", "smaze", "smear", "smell", "smelt", "smews", "smile", "smirk", "smite",
  "smith", "smock", "smogs", "smoke", "smoko", "smoky", "smolt", "smote", "smuts", "snack",
  "snafu", "snags", "snail", "snake", "snaky", "snaps", "snare", "snarf", "snark", "snarl",
  "snash", "snath", "snaws", "sneak", "sneap", "sneck", "sneds", "sneer", "snell", "snibs",
  "snick", "snide", "snies", "sniff", "snigs", "snipe", "snips", "snits", "snobs", "snoek",
  "snog", "snogs", "snood", "snook", "snool", "snoop", "snoot", "snore", "snort", "snots",
  "snout", "snowy", "snubs", "snuck", "snuff", "snugs", "soaks", "soaps", "soapy", "soars",
  "soave", "sober", "socks", "socle", "sodas", "soddy", "sofar", "sofas", "softa", "softs",
  "softy", "soggy", "soils", "soja", "sojas", "sokes", "solan", "solar", "soldi", "soldo",
  "solds", "soled", "soles", "solid", "solo", "solon", "solos", "solve", "somas", "sonar",
  "sonde", "sones", "songs", "sonic", "sonly", "sonny", "sooey", "sooth", "soots", "sooty",
  "soppy", "sorbs", "sored", "soree", "sorel", "sorer", "sores", "sorgo", "sorns", "sorry",
  "sorts", "sotol", "souari", "souari", "souks", "souls", "sound", "soups", "soupy", "sours",
  "souse", "south", "sowar", "sowed", "sower", "soyas", "spake", "space", "spacy", "spade",
  "spado", "spaes", "spahi", "spake", "spale", "spall", "spams", "spand", "spang", "spank",
  "spans", "spare", "spark", "spars", "spas", "spasm", "spate", "spats", "spawn", "spays",
  "speak", "spean", "spear", "speck", "specs", "speed", "speel", "speer", "speir", "spell",
  "spelt", "spend", "spent", "sperm", "spews", "sphene", "spica", "spice", "spick", "spics",
  "spicy", "spied", "spiel", "spier", "spies", "spiff", "spike", "spiks", "spiky", "spile",
  "spill", "spilt", "spims", "spina", "spine", "spins", "spiny", "spire", "spiry", "spite",
  "spits", "spitz", "splat", "splay", "split", "spode", "spoil", "spoke", "spoof", "spook",
  "spool", "spoom", "spoon", "spoor", "spore", "sport", "spots", "spout", "sprag", "sprat",
  "spray", "spree", "sprier", "sprig", "spritz", "sprog", "sprug", "spuds", "spued", "spues",
  "spume", "spumy", "spunk", "spurn", "spurs", "spurt", "sputa", "spyre", "squab", "squad",
  "squat", "squaw", "squeg", "squib", "squid", "squiz", "stabs", "stack", "stade", "staff",
  "stage", "stags", "stagy", "staid", "stain", "stair", "stake", "stale", "stalk", "stall",
  "stamp", "stand", "stang", "stank", "staph", "staps", "stare", "stark", "stars", "start",
  "stash", "state", "stats", "stave", "stays", "stead", "steak", "steal", "steam", "steed",
  "steek", "steel", "steep", "steer", "stein", "stela", "stele", "stems", "steno", "stent",
  "steps", "stere", "stern", "stets", "stews", "stewy", "stick", "stied", "sties", "stiff",
  "stile", "still", "stilt", "stimy", "sting", "stink", "stint", "stipe", "stirk", "stirp",
  "stirs", "stoae", "stoas", "stoat", "stock", "stogy", "stoic", "stoke", "stole", "stoma",
  "stomp", "stone", "stony", "stood", "stool", "stoop", "stops", "store", "stork", "storm",
  "story", "stoss", "stoup", "stour", "stout", "stove", "stows", "strap", "straw", "stray",
  "strep", "strew", "stria", "strip", "stroke", "strop", "strow", "stroy", "strum", "strut",
  "stubs", "stuck", "studs", "study", "stuff", "stull", "stump", "stums", "stung", "stunk",
  "stuns", "stunt", "stupa", "stupe", "sturt", "styes", "style", "styli", "stymy", "suave",
  "subah", "suber", "subly", "succs", "sucks", "sucre", "sudor", "sudsy", "sueded", "suedes",
  "suers", "suety", "sugar", "sughs", "suing", "suint", "suite", "suits", "sulci", "sulfa",
  "sulfo", "sulks", "sulky", "sully", "sumac", "sumos", "sumps", "sumpter", "sunny", "sunup",
  "super", "supes", "supra", "surah", "sural", "suras", "surds", "surer", "surfs", "surfy",
  "surge", "surgy", "surly", "sushi", "swabs", "swage", "swags", "swail", "swain", "swale",
  "swami", "swamy", "swamp", "swans", "swaps", "swarf", "swarm", "swart", "swash", "swath",
  "swats", "sways", "swear", "sweat", "swede", "sweep", "sweer", "sweet", "swell", "swept",
  "swift", "swigs", "swill", "swims", "swine", "swing", "swink", "swipe", "swipy", "swirl",
  "swish", "swiss", "swith", "swits", "swive", "swivel", "swizz", "swobs", "swoon", "swoop",
  "swops", "sword", "swore", "sworn", "swost", "swots", "swoun", "swound", "swung", "sycee",
  "syces", "sykes", "sylph", "sylva", "synch", "syncs", "synes", "synod", "synth", "syren",
  "syrup", "sysop",

  // T
  "taals", "tabby", "table", "taboo", "tabor", "tabun", "tabus", "tacet", "tache", "tacit",
  "tacks", "tacky", "tacos", "tacts", "taels", "taffy", "tafia", "tails", "taint", "taira",
  "taj", "tajes", "takas", "taken", "taker", "takes", "talas", "talcs", "tales", "talks",
  "talky", "tally", "talon", "taluk", "talus", "tamal", "tamed", "tamer", "tames", "tamis",
  "tammy", "tamps", "tanas", "tanga", "tangs", "tango", "tangy", "tanka", "tanks", "tansy",
  "tapas", "taped", "tapen", "taper", "tapes", "tapir", "tapis", "tappa", "tardo", "tardy",
  "tared", "tares", "targe", "tarn", "tarns", "taroc", "tarok", "taros", "tarot", "tarps",
  "tarry", "tarsi", "tarts", "tarty", "tasks", "tasse", "taste", "tasty", "tatar", "tater",
  "tates", "taths", "tatty", "tauld", "taunt", "tauon", "taupe", "tauts", "tavas", "tawed",
  "tawer", "tawie", "tawny", "tawse", "taxed", "taxer", "taxes", "taxi", "taxis", "tazza",
  "tazze", "teach", "teaks", "teals", "teams", "tears", "teary", "tease", "teats", "techy",
  "techs", "teddy", "teels", "teems", "teens", "teeny", "teeth", "teffs", "telco", "teles",
  "telex", "telfer", "telia", "telic", "tells", "telly", "telos", "tempi", "tempo", "temps",
  "tempt", "tench", "tends", "tendu", "tenes", "tenet", "tenia", "tenno", "tenny", "tenon",
  "tenor", "tense", "tenth", "tents", "tents", "tepa", "tepas", "tepee", "tepid", "tepoy",
  "terai", "terce", "teres", "terga", "terms", "terne", "terns", "terra", "terry", "terse",
  "tests", "testa", "testy", "tetra", "tetri", "teugh", "tewed", "texas", "texts", "thack",
  "thaes", "thank", "thars", "thatch", "thats", "thaws", "thawy", "thebe", "theft", "thegn",
  "their", "theme", "thens", "there", "therm", "these", "thesp", "theta", "thews", "thewy",
  "thick", "thief", "thigh", "thill", "thine", "thing", "think", "thins", "thiol", "third",
  "thirl", "thole", "tholi", "thong", "thorn", "thoro", "thorp", "those", "thous", "thrae",
  "thraw", "three", "threw", "throb", "throe", "throne", "throng", "throve", "throw", "thrum",
  "thuds", "thugs", "thuja", "thumb", "thump", "thunk", "thurl", "thuya", "thymi", "thymy",
  "tiara", "tibia", "tical", "ticks", "ticky", "tidal", "tided", "tides", "tiers", "tiffs",
  "tiger", "tight", "tigon", "tikas", "tikes", "tikis", "tikka", "tilak", "tilde", "tiled",
  "tiler", "tiles", "tills", "tilth", "tilts", "timbo", "timed", "timer", "times", "timid",
  "tinct", "tined", "tines", "tinge", "tings", "tints", "tinty", "tipis", "tippy", "tipsy",
  "tired", "tires", "tirls", "tiros", "titan", "titer", "tithe", "title", "titre", "titty",
  "tivy", "tizzy", "toads", "toady", "toast", "today", "toddy", "toed", "toeing", "toffee",
  "toffs", "toffy", "tofts", "tofus", "togae", "togas", "toges", "togged", "toile", "toils",
  "toing", "toked", "tokes", "token", "tolar", "toled", "toles", "tolls", "toluyl", "tombs",
  "tomes", "tommy", "tomtom", "tonal", "toned", "toner", "tones", "tongs", "tonic", "tonne",
  "tools", "toons", "tooth", "toots", "topaz", "toped", "toper", "topes", "topic", "topis",
  "topoi", "topos", "toque", "torah", "toras", "torch", "torcs", "tores", "toric", "torii",
  "toros", "torot", "torrs", "torse", "torsi", "torsk", "torso", "torte", "torts", "torus",
  "tosas", "tossy", "total", "toted", "toter", "totes", "totem", "totty", "touch", "tough",
  "toupee", "tours", "touse", "touts", "towed", "towel", "tower", "towie", "towns", "towny",
  "toxic", "toxin", "toyed", "toyer", "toyon", "toyos", "trabes", "trace", "track", "tract",
  "trade", "trads", "tragi", "trail", "train", "trait", "tramp", "trams", "trans", "traps",
  "trash", "trass", "trave", "trawl", "trays", "tread", "treas", "treat", "treed", "trees",
  "trefa", "treks", "trend", "tress", "trews", "treys", "triad", "trial", "tribe", "trice",
  "trick", "tried", "trier", "tries", "trig", "trike", "trill", "trims", "trinal", "trine",
  "trios", "tripe", "trips", "trite", "troak", "trock", "troll", "tromp", "trona", "tronc",
  "trone", "troop", "trope", "trots", "trout", "trove", "trows", "truce", "truck", "trues",
  "truly", "trump", "trunk", "truss", "trust", "truth", "tryer", "trygon", "tryma", "tryst",
  "tsade", "tsadi", "tsars", "tsked", "tsuba", "tsubo", "tubae", "tubal", "tubas", "tubby",
  "tubed", "tuber", "tubes", "tucks", "tufas", "tuffs", "tufts", "tufty", "tules", "tulip",
  "tulle", "tumid", "tummy", "tumor", "tumps", "tunas", "tunes", "tuned", "tuner", "tungs",
  "tunic", "tunny", "tupik", "tuque", "turbo", "turds", "turfs", "turfy", "turks", "turns",
  "tushy", "tusks", "tutee", "tutor", "tutti", "tutty", "tutus", "twain", "twang", "twas",
  "tweak", "tweed", "tween", "tweet", "twerk", "twerp", "twibill", "twice", "twiddle", "twigs",
  "twill", "twine", "twins", "twirl", "twirp", "twist", "twits", "twixt", "twos", "tying",
  "tykes", "typal", "typed", "types", "typey", "typic", "typo", "typos", "typps", "tyred",
  "tyres", "tyros", "tythe", "tzars",

  // U
  "udder", "udons", "ugali", "ugged", "uhlan", "ukase", "ulama", "ulans", "ulcer", "ulema",
  "ulnae", "ulnar", "ulnas", "ulpan", "ultra", "umbel", "umber", "umbos", "umbra", "umiac",
  "umiak", "umped", "unais", "unapt", "unarm", "unary", "unau", "unbar", "unbid", "unbox",
  "uncap", "uncle", "uncos", "uncus", "uncut", "undee", "under", "undid", "undue", "undug",
  "uneth", "unfed", "unfit", "unfix", "ungod", "ungot", "ungum", "unhat", "unhip", "unify",
  "union", "unite", "units", "unity", "unjam", "unked", "unket", "unkid", "unled", "unleg",
  "unlet", "unlit", "unman", "unmet", "unmew", "unmix", "unpack", "unpeg", "unpen", "unpin",
  "unrid", "unrig", "unrip", "unsay", "unset", "unsew", "unsex", "untie", "until", "untwist",
  "unwed", "unwet", "unwit", "unwon", "unzip", "upbow", "upbye", "updates", "updo", "updos",
  "upend", "upped", "upper", "upset", "upsey", "upter", "uracil", "urare", "urari", "urase",
  "urate", "urban", "urea", "ureas", "uredo", "ureic", "urger", "urges", "urial", "urine",
  "uring", "ursae", "ursid", "ursine", "urson", "usage", "users", "usher", "using", "usnea",
  "usque", "usual", "usurp", "usury", "uteri", "utero", "utile", "utter", "uvea", "uveal",
  "uveas", "uvula",

  // V
  "vacas", "vacua", "vacuo", "vacuum", "vague", "vagus", "vails", "vakil", "vales", "valet",
  "valid", "valis", "valor", "value", "valve", "vamps", "vanda", "vands", "vaned", "vanes",
  "vangs", "vapes", "vapid", "vapor", "varas", "varia", "varie", "varix", "varna", "varus",
  "varve", "vasal", "vases", "vasts", "vatic", "vatu", "vaulted", "vaulting", "vault", "vaunt",
  "vavs", "veals", "vealy", "veena", "veeps", "veers", "veery", "vegan", "vegas", "veggie",
  "veggies", "veils", "veily", "veins", "veiny", "velar", "velds", "veldt", "velum", "vena",
  "venae", "venal", "vends", "venge", "venom", "vents", "venue", "veps", "verbs", "verge",
  "verier", "verily", "verla", "verse", "verso", "verst", "verts", "vertu", "verve", "vesta",
  "vests", "vetch", "vexed", "vexer", "vexes", "vexil", "vials", "viand", "vibes", "vicar",
  "viced", "vices", "video", "viers", "views", "viewy", "viga", "vigas", "vigil", "vigor",
  "vilde", "viler", "villa", "villi", "vills", "vimba", "vimen", "vinal", "vinas", "vinca",
  "vined", "viner", "vines", "viney", "vinic", "vino", "vinos", "vinyl", "viola", "viols",
  "viper", "viral", "vireo", "vires", "virga", "virid", "virl", "virtu", "virus", "visas",
  "vised", "vises", "visit", "visor", "vista", "vital", "vitas", "vitex", "vitro", "vitta",
  "vivas", "vivat", "vivid", "vixen", "vizard", "vizier", "vizir", "vizor", "vocab", "vocal",
  "vodka", "vogie", "vogue", "voice", "voids", "voila", "voile", "volar", "voled", "voles",
  "volet", "volti", "volts", "vomer", "vomit", "voted", "voter", "votes", "vouch", "vowed",
  "vowel", "vower", "voxel", "voyageur", "voyageurs", "vroom", "vrouw", "vrows", "vuggs",
  "vuggy", "vugs", "vulgo", "vulnis", "vulva", "vying",

  // W
  "wabby", "wacke", "wacko", "wacks", "wacky", "wadded", "waddle", "waddy", "waded", "wader",
  "wades", "wadis", "wadmal", "wafer", "waffs", "wafts", "waged", "wager", "wages", "wagon",
  "wahoo", "waifs", "wails", "wains", "waist", "waits", "waive", "waked", "waken", "waker",
  "wakes", "walde", "waled", "waler", "wales", "walks", "walla", "walls", "wally", "waltz",
  "wames", "wammus", "wamus", "wands", "waned", "wanes", "waney", "wangs", "wanly", "wants",
  "warby", "wards", "wared", "wares", "warks", "warms", "warns", "warps", "warty", "warps",
  "warps", "warsle", "warty", "wases", "washy", "wasps", "waspy", "waste", "wasts", "watap",
  "watch", "water", "watts", "wauks", "wauls", "waved", "waver", "waves", "wavey", "wawls",
  "waxed", "waxen", "waxer", "waxes", "wazoo", "weals", "weans", "wears", "weary", "weave",
  "webby", "weber", "wecht", "wedel", "wedge", "wedgy", "weeds", "weedy", "weeks", "weeny",
  "weeps", "weepy", "weest", "weets", "weft", "wefts", "weigh", "weird", "weirs", "welds",
  "wells", "welsh", "welts", "wench", "wends", "wents", "wests", "wetly", "wetters", "wexed",
  "wexes", "whack", "whale", "whams", "whang", "whaps", "wharf", "whats", "whaup", "wheal",
  "wheat", "wheel", "wheen", "wheep", "wheft", "whelk", "whelm", "whelp", "whens", "where",
  "whets", "whews", "wheys", "which", "whiff", "while", "whims", "whine", "whins", "whiny",
  "whips", "whipt", "whirl", "whirr", "whirs", "whish", "whisk", "whist", "white", "whits",
  "whity", "whizz", "whole", "whomp", "whoof", "whoop", "whops", "whore", "whorl", "whort",
  "whose", "whoso", "whump", "whup", "whups", "whyev", "wicca", "wicks", "wicky", "widdy",
  "widen", "wider", "wides", "widow", "width", "wield", "wifed", "wifey", "wifes", "wight",
  "wikis", "wilco", "wilds", "wiled", "wiles", "wilis", "wills", "wilts", "wimps", "wimpy",
  "wince", "winch", "winds", "windy", "wined", "wines", "winey", "wings", "wingy", "winks",
  "wino", "winos", "winze", "wiped", "wiper", "wipes", "wired", "wirer", "wires", "wirra",
  "wised", "wiser", "wises", "wisha", "wisps", "wispy", "wists", "witan", "witch", "withe",
  "withy", "wived", "wiver", "wives", "wizen", "wizes", "woads", "woady", "wodge", "woken",
  "wolds", "wolfs", "woman", "wombat", "wombs", "wonks", "wonky", "woods", "woody", "wooed",
  "wooer", "woofs", "woofy", "wools", "wooly", "woops", "woosh", "woozy", "wordily", "words",
  "wordy", "works", "world", "worms", "wormy", "worry", "worse", "worst", "worth", "would",
  "wound", "woven", "wowed", "wracks", "wraith", "wraps", "wrapt", "wrath", "wreak", "wreck",
  "wrens", "wrest", "wrick", "wried", "wries", "wring", "wrist", "write", "writs", "wrong",
  "wrote", "wroth", "wrung", "wryer", "wryly", "wurst", "wuses", "wusses",

  // X
  "xebec", "xenia", "xenic", "xenon", "xeric", "xerus", "xylan", "xylem", "xylol", "xylyl",
  "xysti", "xysts",

  // Y
  "yacht", "yacks", "yaffs", "yager", "yagis", "yahoo", "yairds", "yamen", "yamun", "yanks",
  "yapok", "yapon", "yards", "yarer", "yarn", "yarns", "yarra", "yauld", "yaups", "yawed",
  "yawls", "yawns", "yawny", "yawps", "yeahs", "yealm", "yeans", "yearn", "years", "yeast",
  "yells", "yelps", "yenta", "yente", "yerba", "yeses", "yetis", "yetts", "yeuks", "yeuky",
  "yield", "yipes", "yipped", "yirth", "ylang", "ylem", "ylems", "yobbo", "yodel", "yodhs",
  "yodle", "yogas", "yogee", "yoghs", "yogic", "yogin", "yogis", "yoked", "yokel", "yokes",
  "yokul", "yolks", "yolky", "yomim", "yonic", "yonis", "yores", "young", "yourn", "yours",
  "youse", "youth", "yowed", "yowes", "yowie", "yowls", "yowza", "yperite", "ypsil", "yuans",
  "yucca", "yucch", "yucky", "yuked", "yukes", "yules", "yummy", "yupon", "yurts", "yutz",

  // Z
  "zaire", "zaman", "zaire", "zappy", "zaps", "zarf", "zarfs", "zayin", "zazen", "zeals",
  "zebec", "zebra", "zebub", "zebus", "zeins", "zeppelin", "zerda", "zerks", "zeros", "zest",
  "zests", "zesty", "zetas", "zibet", "zilch", "zills", "zincs", "zincy", "zinged", "zingy",
  "zinky", "zippo", "zippy", "ziram", "zitis", "zizit", "zlote", "zloty", "zoaea", "zoeae",
  "zoeas", "zoeal", "zoism", "zoist", "zombi", "zonal", "zoned", "zoner", "zones", "zonks",
  "zooid", "zooks", "zooms", "zoona", "zooty", "zorch", "zoril", "zoris", "zouks", "zowie",
  "zuhrs", "zupan", "zuppa", "zuppas", "zydeco", "zygal", "zymes",
];

/**
 * Backward-compat alias. The daily-picker module imports `WORDS` and
 * uses `WORDS[hash % WORDS.length]` to pick the answer — only the
 * curated answer pool should ever be answers.
 */
export const WORDS = ANSWER_WORDS;

/** Union of both lists, lowercased, for O(1) guess validation. */
export const WORD_SET: ReadonlySet<string> = new Set([
  ...ANSWER_WORDS,
  ...EXTRA_GUESSES,
]);

export function isValidGuess(word: string): boolean {
  return WORD_SET.has(word.toLowerCase());
}
